// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/add_generate_directive (interfaces: Foo)
//
// Generated by this command:
//
//	mockgen -write_generate_directive -destination mockgen/internal/tests/add_generate_directive/mock.go -package add_generate_directive github.com/canonical/gomock/mockgen/internal/tests/add_generate_directive Foo
//

// Package add_generate_directive is a generated GoMock package.
package add_generate_directive

import (
	gomock "github.com/canonical/gomock/gomock"
)

//go:generate mockgen -write_generate_directive -destination mockgen/internal/tests/add_generate_directive/mock.go -package add_generate_directive github.com/canonical/gomock/mockgen/internal/tests/add_generate_directive Foo

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
	isgomock struct{}
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock       *MockFoo
	barExpects []*gomock.Call2_0[[]string, chan<- Message]
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockFoo) Bar(channels []string, message chan<- Message) {
	m.ctrl.T.Helper()
	gomock.Dispatch2_0(&m.recorder.barExpects, m.ctrl, m, "Bar", channels, message)
}

// Bar indicates an expected call of Bar.
func (mr *MockFooMockRecorder) Bar(channels, message any) *MockFooBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_0[[]string, chan<- Message](mr.mock.ctrl.T, mr.mock, "Bar", gomock.EnsureMatcher(channels), gomock.EnsureMatcher(message))
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFooBarCall is the typed call wrapper for Bar.
type MockFooBarCall = gomock.Call2_0[[]string, chan<- Message]
