// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/sample/concurrent (interfaces: Math)
//
// Generated by this command:
//
//	mockgen -destination mock/concurrent_mock.go github.com/canonical/gomock/sample/concurrent Math
//

// Package mock_concurrent is a generated GoMock package.
package mock_concurrent

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockMath is a mock of Math interface.
type MockMath struct {
	ctrl     *gomock.Controller
	recorder *MockMathMockRecorder
	isgomock struct{}
}

// MockMathMockRecorder is the mock recorder for MockMath.
type MockMathMockRecorder struct {
	mock       *MockMath
	sumExpects []*gomock.Call2_1[int, int, int]
}

// NewMockMath creates a new mock instance.
func NewMockMath(ctrl *gomock.Controller) *MockMath {
	mock := &MockMath{ctrl: ctrl}
	mock.recorder = &MockMathMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMath) EXPECT() *MockMathMockRecorder {
	return m.recorder
}

// Sum mocks base method.
func (m *MockMath) Sum(a, b int) int {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.sumExpects, m.ctrl, m, "Sum", a, b)
}

// Sum indicates an expected call of Sum.
func (mr *MockMathMockRecorder) Sum(a, b any) *MockMathSumCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[int, int, int](mr.mock.ctrl.T, mr.mock, "Sum", gomock.EnsureMatcher(a), gomock.EnsureMatcher(b))
	mr.sumExpects = append(mr.sumExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMathSumCall is the typed call wrapper for Sum.
type MockMathSumCall = gomock.Call2_1[int, int, int]
