// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/dot_imports (interfaces: WithDotImports)
//
// Generated by this command:
//
//	mockgen -package dot_imports -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/dot_imports WithDotImports
//

// Package dot_imports is a generated GoMock package.
package dot_imports

import (
	bytes "bytes"
	context "context"
	http "net/http"

	gomock "github.com/canonical/gomock/gomock"
)

// MockWithDotImports is a mock of WithDotImports interface.
type MockWithDotImports struct {
	ctrl     *gomock.Controller
	recorder *MockWithDotImportsMockRecorder
	isgomock struct{}
}

// MockWithDotImportsMockRecorder is the mock recorder for MockWithDotImports.
type MockWithDotImportsMockRecorder struct {
	mock           *MockWithDotImports
	method1Expects []*gomock.Call0_1[http.Request]
	method2Expects []*gomock.Call0_1[*bytes.Buffer]
	method3Expects []*gomock.Call0_1[context.Context]
}

// NewMockWithDotImports creates a new mock instance.
func NewMockWithDotImports(ctrl *gomock.Controller) *MockWithDotImports {
	mock := &MockWithDotImports{ctrl: ctrl}
	mock.recorder = &MockWithDotImportsMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithDotImports) EXPECT() *MockWithDotImportsMockRecorder {
	return m.recorder
}

// Method1 mocks base method.
func (m *MockWithDotImports) Method1() http.Request {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.method1Expects, m.ctrl, m, "Method1")
}

// Method1 indicates an expected call of Method1.
func (mr *MockWithDotImportsMockRecorder) Method1() *MockWithDotImportsMethod1Call {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[http.Request](mr.mock.ctrl.T, mr.mock, "Method1")
	mr.method1Expects = append(mr.method1Expects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWithDotImportsMethod1Call is the typed call wrapper for Method1.
type MockWithDotImportsMethod1Call = gomock.Call0_1[http.Request]

// Method2 mocks base method.
func (m *MockWithDotImports) Method2() *bytes.Buffer {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.method2Expects, m.ctrl, m, "Method2")
}

// Method2 indicates an expected call of Method2.
func (mr *MockWithDotImportsMockRecorder) Method2() *MockWithDotImportsMethod2Call {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[*bytes.Buffer](mr.mock.ctrl.T, mr.mock, "Method2")
	mr.method2Expects = append(mr.method2Expects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWithDotImportsMethod2Call is the typed call wrapper for Method2.
type MockWithDotImportsMethod2Call = gomock.Call0_1[*bytes.Buffer]

// Method3 mocks base method.
func (m *MockWithDotImports) Method3() context.Context {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.method3Expects, m.ctrl, m, "Method3")
}

// Method3 indicates an expected call of Method3.
func (mr *MockWithDotImportsMockRecorder) Method3() *MockWithDotImportsMethod3Call {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[context.Context](mr.mock.ctrl.T, mr.mock, "Method3")
	mr.method3Expects = append(mr.method3Expects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWithDotImportsMethod3Call is the typed call wrapper for Method3.
type MockWithDotImportsMethod3Call = gomock.Call0_1[context.Context]
