// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_source/definition (interfaces: S)
//
// Generated by this command:
//
//	mockgen -package source -destination source_mock.go github.com/canonical/gomock/mockgen/internal/tests/import_source/definition S
//

// Package source is a generated GoMock package.
package source

import (
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
)

// MockS is a mock of S interface.
type MockS struct {
	ctrl     *gomock.Controller
	recorder *MockSMockRecorder
	isgomock struct{}
}

// MockSMockRecorder is the mock recorder for MockS.
type MockSMockRecorder struct {
	mock *MockS
}

// NewMockS creates a new mock instance.
func NewMockS(ctrl *gomock.Controller) *MockS {
	mock := &MockS{ctrl: ctrl}
	mock.recorder = &MockSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS) EXPECT() *MockSMockRecorder {
	return m.recorder
}

// F mocks base method.
func (m *MockS) F(arg0 X) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "F", arg0)
}

// F indicates an expected call of F.
func (mr *MockSMockRecorder) F(arg0 any) *MockSFCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "F", reflect.TypeOf((*MockS)(nil).F), arg0)
	return &MockSFCall{Call: call}
}

// MockSFCall is the typed call wrapper for F.
type MockSFCall = gomock.Call1_0[X]
