// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/overlapping_methods (interfaces: ReadWriteCloser)
//
// Generated by this command:
//
//	mockgen -package overlap -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/overlapping_methods ReadWriteCloser
//

// Package overlap is a generated GoMock package.
package overlap

import (
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
)

// MockReadWriteCloser is a mock of ReadWriteCloser interface.
type MockReadWriteCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriteCloserMockRecorder
	isgomock struct{}
}

// MockReadWriteCloserMockRecorder is the mock recorder for MockReadWriteCloser.
type MockReadWriteCloserMockRecorder struct {
	mock *MockReadWriteCloser
}

// NewMockReadWriteCloser creates a new mock instance.
func NewMockReadWriteCloser(ctrl *gomock.Controller) *MockReadWriteCloser {
	mock := &MockReadWriteCloser{ctrl: ctrl}
	mock.recorder = &MockReadWriteCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriteCloser) EXPECT() *MockReadWriteCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadWriteCloser) Close() error {
	m.ctrl.T.Helper()
	return gomock.Invoke1[error](m.ctrl.Call(m, "Close"))
}

// Close indicates an expected call of Close.
func (mr *MockReadWriteCloserMockRecorder) Close() *MockReadWriteCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReadWriteCloser)(nil).Close))
	return &MockReadWriteCloserCloseCall{Call: call}
}

// MockReadWriteCloserCloseCall is the typed call wrapper for Close.
type MockReadWriteCloserCloseCall = gomock.Call0_1[error]

// Read mocks base method.
func (m *MockReadWriteCloser) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Invoke2[int, error](m.ctrl.Call(m, "Read", arg0))
}

// Read indicates an expected call of Read.
func (mr *MockReadWriteCloserMockRecorder) Read(arg0 any) *MockReadWriteCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadWriteCloser)(nil).Read), arg0)
	return &MockReadWriteCloserReadCall{Call: call}
}

// MockReadWriteCloserReadCall is the typed call wrapper for Read.
type MockReadWriteCloserReadCall = gomock.Call1_2[[]byte, int, error]

// Write mocks base method.
func (m *MockReadWriteCloser) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Invoke2[int, error](m.ctrl.Call(m, "Write", arg0))
}

// Write indicates an expected call of Write.
func (mr *MockReadWriteCloserMockRecorder) Write(arg0 any) *MockReadWriteCloserWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockReadWriteCloser)(nil).Write), arg0)
	return &MockReadWriteCloserWriteCall{Call: call}
}

// MockReadWriteCloserWriteCall is the typed call wrapper for Write.
type MockReadWriteCloserWriteCall = gomock.Call1_2[[]byte, int, error]
