// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/overlapping_methods (interfaces: ReadWriteCloser)
//
// Generated by this command:
//
//	mockgen -package overlap -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/overlapping_methods ReadWriteCloser
//

// Package overlap is a generated GoMock package.
package overlap

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockReadWriteCloser is a mock of ReadWriteCloser interface.
type MockReadWriteCloser struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriteCloserMockRecorder
	isgomock struct{}
}

// MockReadWriteCloserMockRecorder is the mock recorder for MockReadWriteCloser.
type MockReadWriteCloserMockRecorder struct {
	mock         *MockReadWriteCloser
	closeExpects []*gomock.Call0_1[error]
	readExpects  []*gomock.Call1_2[[]byte, int, error]
	writeExpects []*gomock.Call1_2[[]byte, int, error]
}

// NewMockReadWriteCloser creates a new mock instance.
func NewMockReadWriteCloser(ctrl *gomock.Controller) *MockReadWriteCloser {
	mock := &MockReadWriteCloser{ctrl: ctrl}
	mock.recorder = &MockReadWriteCloserMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriteCloser) EXPECT() *MockReadWriteCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockReadWriteCloser) Close() error {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.closeExpects, m.ctrl, m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockReadWriteCloserMockRecorder) Close() *MockReadWriteCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[error](mr.mock.ctrl.T, mr.mock, "Close")
	mr.closeExpects = append(mr.closeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockReadWriteCloserCloseCall is the typed call wrapper for Close.
type MockReadWriteCloserCloseCall = gomock.Call0_1[error]

// Read mocks base method.
func (m *MockReadWriteCloser) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.readExpects, m.ctrl, m, "Read", arg0)
}

// Read indicates an expected call of Read.
func (mr *MockReadWriteCloserMockRecorder) Read(arg0 any) *MockReadWriteCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[[]byte, int, error](mr.mock.ctrl.T, mr.mock, "Read", gomock.EnsureMatcher(arg0))
	mr.readExpects = append(mr.readExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockReadWriteCloserReadCall is the typed call wrapper for Read.
type MockReadWriteCloserReadCall = gomock.Call1_2[[]byte, int, error]

// Write mocks base method.
func (m *MockReadWriteCloser) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.writeExpects, m.ctrl, m, "Write", arg0)
}

// Write indicates an expected call of Write.
func (mr *MockReadWriteCloserMockRecorder) Write(arg0 any) *MockReadWriteCloserWriteCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[[]byte, int, error](mr.mock.ctrl.T, mr.mock, "Write", gomock.EnsureMatcher(arg0))
	mr.writeExpects = append(mr.writeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockReadWriteCloserWriteCall is the typed call wrapper for Write.
type MockReadWriteCloserWriteCall = gomock.Call1_2[[]byte, int, error]
