// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/defined_import_local_name (interfaces: WithImports)
//
// Generated by this command:
//
//	mockgen -package defined_import_local_name -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/defined_import_local_name WithImports
//

// Package defined_import_local_name is a generated GoMock package.
package defined_import_local_name

import (
	bytes "bytes"
	context "context"

	gomock "github.com/canonical/gomock/gomock"
)

// MockWithImports is a mock of WithImports interface.
type MockWithImports struct {
	ctrl     *gomock.Controller
	recorder *MockWithImportsMockRecorder
	isgomock struct{}
}

// MockWithImportsMockRecorder is the mock recorder for MockWithImports.
type MockWithImportsMockRecorder struct {
	mock           *MockWithImports
	method1Expects []*gomock.Call0_1[bytes.Buffer]
	method2Expects []*gomock.Call0_1[context.Context]
}

// NewMockWithImports creates a new mock instance.
func NewMockWithImports(ctrl *gomock.Controller) *MockWithImports {
	mock := &MockWithImports{ctrl: ctrl}
	mock.recorder = &MockWithImportsMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithImports) EXPECT() *MockWithImportsMockRecorder {
	return m.recorder
}

// Method1 mocks base method.
func (m *MockWithImports) Method1() bytes.Buffer {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.method1Expects, m.ctrl, m, "Method1")
}

// Method1 indicates an expected call of Method1.
func (mr *MockWithImportsMockRecorder) Method1() *MockWithImportsMethod1Call {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[bytes.Buffer](mr.mock.ctrl.T, mr.mock, "Method1")
	mr.method1Expects = append(mr.method1Expects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWithImportsMethod1Call is the typed call wrapper for Method1.
type MockWithImportsMethod1Call = gomock.Call0_1[bytes.Buffer]

// Method2 mocks base method.
func (m *MockWithImports) Method2() context.Context {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.method2Expects, m.ctrl, m, "Method2")
}

// Method2 indicates an expected call of Method2.
func (mr *MockWithImportsMockRecorder) Method2() *MockWithImportsMethod2Call {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[context.Context](mr.mock.ctrl.T, mr.mock, "Method2")
	mr.method2Expects = append(mr.method2Expects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWithImportsMethod2Call is the typed call wrapper for Method2.
type MockWithImportsMethod2Call = gomock.Call0_1[context.Context]
