// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/mock_name/post (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names=Service=PostServiceMock -package mocks -destination mocks/post_service.go -self_package github.com/canonical/gomock/mockgen/internal/tests/mock_name/mocks github.com/canonical/gomock/mockgen/internal/tests/mock_name/post Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
	post "github.com/canonical/gomock/mockgen/internal/tests/mock_name/post"
	user "github.com/canonical/gomock/mockgen/internal/tests/mock_name/user"
)

// PostServiceMock is a mock of Service interface.
type PostServiceMock struct {
	ctrl     *gomock.Controller
	recorder *PostServiceMockMockRecorder
	isgomock struct{}
}

// PostServiceMockMockRecorder is the mock recorder for PostServiceMock.
type PostServiceMockMockRecorder struct {
	mock *PostServiceMock
}

// NewPostServiceMock creates a new mock instance.
func NewPostServiceMock(ctrl *gomock.Controller) *PostServiceMock {
	mock := &PostServiceMock{ctrl: ctrl}
	mock.recorder = &PostServiceMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PostServiceMock) EXPECT() *PostServiceMockMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *PostServiceMock) Create(title, body string, author *user.User) (*post.Post, error) {
	m.ctrl.T.Helper()
	return gomock.Invoke2[*post.Post, error](m.ctrl.Call(m, "Create", title, body, author))
}

// Create indicates an expected call of Create.
func (mr *PostServiceMockMockRecorder) Create(title, body, author any) *PostServiceMockCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*PostServiceMock)(nil).Create), title, body, author)
	return &PostServiceMockCreateCall{Call: call}
}

// PostServiceMockCreateCall is the typed call wrapper for Create.
type PostServiceMockCreateCall = gomock.Call3_2[string, string, *user.User, *post.Post, error]
