// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/mock_name/user (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names=Service=UserServiceMock -package mocks -destination mocks/user_service.go -self_package github.com/canonical/gomock/mockgen/internal/tests/mock_name/mocks github.com/canonical/gomock/mockgen/internal/tests/mock_name/user Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/canonical/gomock/gomock"
	user "github.com/canonical/gomock/mockgen/internal/tests/mock_name/user"
)

// UserServiceMock is a mock of Service interface.
type UserServiceMock struct {
	ctrl     *gomock.Controller
	recorder *UserServiceMockMockRecorder
	isgomock struct{}
}

// UserServiceMockMockRecorder is the mock recorder for UserServiceMock.
type UserServiceMockMockRecorder struct {
	mock          *UserServiceMock
	createExpects []*gomock.Call1_2[string, *user.User, error]
}

// NewUserServiceMock creates a new mock instance.
func NewUserServiceMock(ctrl *gomock.Controller) *UserServiceMock {
	mock := &UserServiceMock{ctrl: ctrl}
	mock.recorder = &UserServiceMockMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserServiceMock) EXPECT() *UserServiceMockMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *UserServiceMock) Create(name string) (*user.User, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.createExpects, m.ctrl, m, "Create", name)
}

// Create indicates an expected call of Create.
func (mr *UserServiceMockMockRecorder) Create(name any) *UserServiceMockCreateCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[string, *user.User, error](mr.mock.ctrl.T, mr.mock, "Create", gomock.EnsureMatcher(name))
	mr.createExpects = append(mr.createExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// UserServiceMockCreateCall is the typed call wrapper for Create.
type UserServiceMockCreateCall = gomock.Call1_2[string, *user.User, error]
