// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/alias (interfaces: Fooer,FooerAlias,Barer,BarerAlias,Bazer,QuxerConsumer,QuuxerConsumer)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/interfaces.go . Fooer,FooerAlias,Barer,BarerAlias,Bazer,QuxerConsumer,QuuxerConsumer
//

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/canonical/gomock/gomock"
	alias "github.com/canonical/gomock/mockgen/internal/tests/alias"
	subpkg "github.com/canonical/gomock/mockgen/internal/tests/alias/subpkg"
)

// MockFooer is a mock of Fooer interface.
type MockFooer struct {
	ctrl     *gomock.Controller
	recorder *MockFooerMockRecorder
	isgomock struct{}
}

// MockFooerMockRecorder is the mock recorder for MockFooer.
type MockFooerMockRecorder struct {
	mock       *MockFooer
	fooExpects []*gomock.Call0_0
}

// NewMockFooer creates a new mock instance.
func NewMockFooer(ctrl *gomock.Controller) *MockFooer {
	mock := &MockFooer{ctrl: ctrl}
	mock.recorder = &MockFooerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooer) EXPECT() *MockFooerMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockFooer) Foo() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.fooExpects, m.ctrl, m, "Foo")
}

// Foo indicates an expected call of Foo.
func (mr *MockFooerMockRecorder) Foo() *MockFooerFooCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Foo")
	mr.fooExpects = append(mr.fooExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFooerFooCall is the typed call wrapper for Foo.
type MockFooerFooCall = gomock.Call0_0

// MockFooerAlias is a mock of FooerAlias interface.
type MockFooerAlias struct {
	ctrl     *gomock.Controller
	recorder *MockFooerAliasMockRecorder
	isgomock struct{}
}

// MockFooerAliasMockRecorder is the mock recorder for MockFooerAlias.
type MockFooerAliasMockRecorder struct {
	mock       *MockFooerAlias
	fooExpects []*gomock.Call0_0
}

// NewMockFooerAlias creates a new mock instance.
func NewMockFooerAlias(ctrl *gomock.Controller) *MockFooerAlias {
	mock := &MockFooerAlias{ctrl: ctrl}
	mock.recorder = &MockFooerAliasMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooerAlias) EXPECT() *MockFooerAliasMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockFooerAlias) Foo() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.fooExpects, m.ctrl, m, "Foo")
}

// Foo indicates an expected call of Foo.
func (mr *MockFooerAliasMockRecorder) Foo() *MockFooerAliasFooCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Foo")
	mr.fooExpects = append(mr.fooExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFooerAliasFooCall is the typed call wrapper for Foo.
type MockFooerAliasFooCall = gomock.Call0_0

// MockBarer is a mock of Barer interface.
type MockBarer struct {
	ctrl     *gomock.Controller
	recorder *MockBarerMockRecorder
	isgomock struct{}
}

// MockBarerMockRecorder is the mock recorder for MockBarer.
type MockBarerMockRecorder struct {
	mock       *MockBarer
	barExpects []*gomock.Call1_1[alias.FooerAlias, alias.FooerAlias]
}

// NewMockBarer creates a new mock instance.
func NewMockBarer(ctrl *gomock.Controller) *MockBarer {
	mock := &MockBarer{ctrl: ctrl}
	mock.recorder = &MockBarerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarer) EXPECT() *MockBarerMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockBarer) Bar(arg0 alias.FooerAlias) alias.FooerAlias {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.barExpects, m.ctrl, m, "Bar", arg0)
}

// Bar indicates an expected call of Bar.
func (mr *MockBarerMockRecorder) Bar(arg0 any) *MockBarerBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[alias.FooerAlias, alias.FooerAlias](mr.mock.ctrl.T, mr.mock, "Bar", gomock.EnsureMatcher(arg0))
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarerBarCall is the typed call wrapper for Bar.
type MockBarerBarCall = gomock.Call1_1[alias.FooerAlias, alias.FooerAlias]

// MockBarerAlias is a mock of BarerAlias interface.
type MockBarerAlias struct {
	ctrl     *gomock.Controller
	recorder *MockBarerAliasMockRecorder
	isgomock struct{}
}

// MockBarerAliasMockRecorder is the mock recorder for MockBarerAlias.
type MockBarerAliasMockRecorder struct {
	mock       *MockBarerAlias
	barExpects []*gomock.Call1_1[alias.FooerAlias, alias.FooerAlias]
}

// NewMockBarerAlias creates a new mock instance.
func NewMockBarerAlias(ctrl *gomock.Controller) *MockBarerAlias {
	mock := &MockBarerAlias{ctrl: ctrl}
	mock.recorder = &MockBarerAliasMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarerAlias) EXPECT() *MockBarerAliasMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockBarerAlias) Bar(arg0 alias.FooerAlias) alias.FooerAlias {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.barExpects, m.ctrl, m, "Bar", arg0)
}

// Bar indicates an expected call of Bar.
func (mr *MockBarerAliasMockRecorder) Bar(arg0 any) *MockBarerAliasBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[alias.FooerAlias, alias.FooerAlias](mr.mock.ctrl.T, mr.mock, "Bar", gomock.EnsureMatcher(arg0))
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarerAliasBarCall is the typed call wrapper for Bar.
type MockBarerAliasBarCall = gomock.Call1_1[alias.FooerAlias, alias.FooerAlias]

// MockBazer is a mock of Bazer interface.
type MockBazer struct {
	ctrl     *gomock.Controller
	recorder *MockBazerMockRecorder
	isgomock struct{}
}

// MockBazerMockRecorder is the mock recorder for MockBazer.
type MockBazerMockRecorder struct {
	mock       *MockBazer
	bazExpects []*gomock.Call1_1[alias.Fooer, alias.Fooer]
}

// NewMockBazer creates a new mock instance.
func NewMockBazer(ctrl *gomock.Controller) *MockBazer {
	mock := &MockBazer{ctrl: ctrl}
	mock.recorder = &MockBazerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBazer) EXPECT() *MockBazerMockRecorder {
	return m.recorder
}

// Baz mocks base method.
func (m *MockBazer) Baz(arg0 alias.Fooer) alias.Fooer {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.bazExpects, m.ctrl, m, "Baz", arg0)
}

// Baz indicates an expected call of Baz.
func (mr *MockBazerMockRecorder) Baz(arg0 any) *MockBazerBazCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[alias.Fooer, alias.Fooer](mr.mock.ctrl.T, mr.mock, "Baz", gomock.EnsureMatcher(arg0))
	mr.bazExpects = append(mr.bazExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBazerBazCall is the typed call wrapper for Baz.
type MockBazerBazCall = gomock.Call1_1[alias.Fooer, alias.Fooer]

// MockQuxerConsumer is a mock of QuxerConsumer interface.
type MockQuxerConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockQuxerConsumerMockRecorder
	isgomock struct{}
}

// MockQuxerConsumerMockRecorder is the mock recorder for MockQuxerConsumer.
type MockQuxerConsumerMockRecorder struct {
	mock           *MockQuxerConsumer
	consumeExpects []*gomock.Call1_1[alias.QuxerAlias, alias.QuxerAlias]
}

// NewMockQuxerConsumer creates a new mock instance.
func NewMockQuxerConsumer(ctrl *gomock.Controller) *MockQuxerConsumer {
	mock := &MockQuxerConsumer{ctrl: ctrl}
	mock.recorder = &MockQuxerConsumerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuxerConsumer) EXPECT() *MockQuxerConsumerMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockQuxerConsumer) Consume(arg0 alias.QuxerAlias) alias.QuxerAlias {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.consumeExpects, m.ctrl, m, "Consume", arg0)
}

// Consume indicates an expected call of Consume.
func (mr *MockQuxerConsumerMockRecorder) Consume(arg0 any) *MockQuxerConsumerConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[alias.QuxerAlias, alias.QuxerAlias](mr.mock.ctrl.T, mr.mock, "Consume", gomock.EnsureMatcher(arg0))
	mr.consumeExpects = append(mr.consumeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockQuxerConsumerConsumeCall is the typed call wrapper for Consume.
type MockQuxerConsumerConsumeCall = gomock.Call1_1[alias.QuxerAlias, alias.QuxerAlias]

// MockQuuxerConsumer is a mock of QuuxerConsumer interface.
type MockQuuxerConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockQuuxerConsumerMockRecorder
	isgomock struct{}
}

// MockQuuxerConsumerMockRecorder is the mock recorder for MockQuuxerConsumer.
type MockQuuxerConsumerMockRecorder struct {
	mock           *MockQuuxerConsumer
	consumeExpects []*gomock.Call1_1[subpkg.Quuxer, subpkg.Quuxer]
}

// NewMockQuuxerConsumer creates a new mock instance.
func NewMockQuuxerConsumer(ctrl *gomock.Controller) *MockQuuxerConsumer {
	mock := &MockQuuxerConsumer{ctrl: ctrl}
	mock.recorder = &MockQuuxerConsumerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuuxerConsumer) EXPECT() *MockQuuxerConsumerMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockQuuxerConsumer) Consume(arg0 subpkg.Quuxer) subpkg.Quuxer {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.consumeExpects, m.ctrl, m, "Consume", arg0)
}

// Consume indicates an expected call of Consume.
func (mr *MockQuuxerConsumerMockRecorder) Consume(arg0 any) *MockQuuxerConsumerConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[subpkg.Quuxer, subpkg.Quuxer](mr.mock.ctrl.T, mr.mock, "Consume", gomock.EnsureMatcher(arg0))
	mr.consumeExpects = append(mr.consumeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockQuuxerConsumerConsumeCall is the typed call wrapper for Consume.
type MockQuuxerConsumerConsumeCall = gomock.Call1_1[subpkg.Quuxer, subpkg.Quuxer]
