// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/package_mode (interfaces: Food,Eater,Animal,Human,Primate,Car,Driver,UrbanResident,Farmer,Earth)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/interfaces.go . Food,Eater,Animal,Human,Primate,Car,Driver,UrbanResident,Farmer,Earth
//

// Package mock is a generated GoMock package.
package mock

import (
	time "time"

	gomock "github.com/canonical/gomock/gomock"
	package_mode "github.com/canonical/gomock/mockgen/internal/tests/package_mode"
	cars "github.com/canonical/gomock/mockgen/internal/tests/package_mode/cars"
	fuel "github.com/canonical/gomock/mockgen/internal/tests/package_mode/fuel"
)

// MockFood is a mock of Food interface.
type MockFood struct {
	ctrl     *gomock.Controller
	recorder *MockFoodMockRecorder
	isgomock struct{}
}

// MockFoodMockRecorder is the mock recorder for MockFood.
type MockFoodMockRecorder struct {
	mock            *MockFood
	caloriesExpects []*gomock.Call0_1[int]
}

// NewMockFood creates a new mock instance.
func NewMockFood(ctrl *gomock.Controller) *MockFood {
	mock := &MockFood{ctrl: ctrl}
	mock.recorder = &MockFoodMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFood) EXPECT() *MockFoodMockRecorder {
	return m.recorder
}

// Calories mocks base method.
func (m *MockFood) Calories() int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.caloriesExpects, m.ctrl, m, "Calories")
}

// Calories indicates an expected call of Calories.
func (mr *MockFoodMockRecorder) Calories() *MockFoodCaloriesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[int](mr.mock.ctrl.T, mr.mock, "Calories")
	mr.caloriesExpects = append(mr.caloriesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFoodCaloriesCall is the typed call wrapper for Calories.
type MockFoodCaloriesCall = gomock.Call0_1[int]

// MockEater is a mock of Eater interface.
type MockEater struct {
	ctrl     *gomock.Controller
	recorder *MockEaterMockRecorder
	isgomock struct{}
}

// MockEaterMockRecorder is the mock recorder for MockEater.
type MockEaterMockRecorder struct {
	mock       *MockEater
	eatExpects []*gomock.Call0V_0[package_mode.Food]
}

// NewMockEater creates a new mock instance.
func NewMockEater(ctrl *gomock.Controller) *MockEater {
	mock := &MockEater{ctrl: ctrl}
	mock.recorder = &MockEaterMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEater) EXPECT() *MockEaterMockRecorder {
	return m.recorder
}

// Eat mocks base method.
func (m *MockEater) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockEaterMockRecorder) Eat(foods ...any) *MockEaterEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockEaterEatCall is the typed call wrapper for Eat.
type MockEaterEatCall = gomock.Call0V_0[package_mode.Food]

// MockAnimal is a mock of Animal interface.
type MockAnimal struct {
	ctrl     *gomock.Controller
	recorder *MockAnimalMockRecorder
	isgomock struct{}
}

// MockAnimalMockRecorder is the mock recorder for MockAnimal.
type MockAnimalMockRecorder struct {
	mock           *MockAnimal
	breatheExpects []*gomock.Call0_0
	eatExpects     []*gomock.Call0V_0[package_mode.Food]
	sleepExpects   []*gomock.Call1_0[time.Duration]
}

// NewMockAnimal creates a new mock instance.
func NewMockAnimal(ctrl *gomock.Controller) *MockAnimal {
	mock := &MockAnimal{ctrl: ctrl}
	mock.recorder = &MockAnimalMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimal) EXPECT() *MockAnimalMockRecorder {
	return m.recorder
}

// Breathe mocks base method.
func (m *MockAnimal) Breathe() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.breatheExpects, m.ctrl, m, "Breathe")
}

// Breathe indicates an expected call of Breathe.
func (mr *MockAnimalMockRecorder) Breathe() *MockAnimalBreatheCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Breathe")
	mr.breatheExpects = append(mr.breatheExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAnimalBreatheCall is the typed call wrapper for Breathe.
type MockAnimalBreatheCall = gomock.Call0_0

// Eat mocks base method.
func (m *MockAnimal) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockAnimalMockRecorder) Eat(foods ...any) *MockAnimalEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAnimalEatCall is the typed call wrapper for Eat.
type MockAnimalEatCall = gomock.Call0V_0[package_mode.Food]

// Sleep mocks base method.
func (m *MockAnimal) Sleep(duration time.Duration) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.sleepExpects, m.ctrl, m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockAnimalMockRecorder) Sleep(duration any) *MockAnimalSleepCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[time.Duration](mr.mock.ctrl.T, mr.mock, "Sleep", gomock.EnsureMatcher(duration))
	mr.sleepExpects = append(mr.sleepExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAnimalSleepCall is the typed call wrapper for Sleep.
type MockAnimalSleepCall = gomock.Call1_0[time.Duration]

// MockHuman is a mock of Human interface.
type MockHuman struct {
	ctrl     *gomock.Controller
	recorder *MockHumanMockRecorder
	isgomock struct{}
}

// MockHumanMockRecorder is the mock recorder for MockHuman.
type MockHumanMockRecorder struct {
	mock           *MockHuman
	breatheExpects []*gomock.Call0_0
	eatExpects     []*gomock.Call0V_0[package_mode.Food]
	sleepExpects   []*gomock.Call1_0[time.Duration]
}

// NewMockHuman creates a new mock instance.
func NewMockHuman(ctrl *gomock.Controller) *MockHuman {
	mock := &MockHuman{ctrl: ctrl}
	mock.recorder = &MockHumanMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHuman) EXPECT() *MockHumanMockRecorder {
	return m.recorder
}

// Breathe mocks base method.
func (m *MockHuman) Breathe() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.breatheExpects, m.ctrl, m, "Breathe")
}

// Breathe indicates an expected call of Breathe.
func (mr *MockHumanMockRecorder) Breathe() *MockHumanBreatheCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Breathe")
	mr.breatheExpects = append(mr.breatheExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockHumanBreatheCall is the typed call wrapper for Breathe.
type MockHumanBreatheCall = gomock.Call0_0

// Eat mocks base method.
func (m *MockHuman) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockHumanMockRecorder) Eat(foods ...any) *MockHumanEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockHumanEatCall is the typed call wrapper for Eat.
type MockHumanEatCall = gomock.Call0V_0[package_mode.Food]

// Sleep mocks base method.
func (m *MockHuman) Sleep(duration time.Duration) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.sleepExpects, m.ctrl, m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockHumanMockRecorder) Sleep(duration any) *MockHumanSleepCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[time.Duration](mr.mock.ctrl.T, mr.mock, "Sleep", gomock.EnsureMatcher(duration))
	mr.sleepExpects = append(mr.sleepExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockHumanSleepCall is the typed call wrapper for Sleep.
type MockHumanSleepCall = gomock.Call1_0[time.Duration]

// MockPrimate is a mock of Primate interface.
type MockPrimate struct {
	ctrl     *gomock.Controller
	recorder *MockPrimateMockRecorder
	isgomock struct{}
}

// MockPrimateMockRecorder is the mock recorder for MockPrimate.
type MockPrimateMockRecorder struct {
	mock           *MockPrimate
	breatheExpects []*gomock.Call0_0
	eatExpects     []*gomock.Call0V_0[package_mode.Food]
	sleepExpects   []*gomock.Call1_0[time.Duration]
}

// NewMockPrimate creates a new mock instance.
func NewMockPrimate(ctrl *gomock.Controller) *MockPrimate {
	mock := &MockPrimate{ctrl: ctrl}
	mock.recorder = &MockPrimateMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrimate) EXPECT() *MockPrimateMockRecorder {
	return m.recorder
}

// Breathe mocks base method.
func (m *MockPrimate) Breathe() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.breatheExpects, m.ctrl, m, "Breathe")
}

// Breathe indicates an expected call of Breathe.
func (mr *MockPrimateMockRecorder) Breathe() *MockPrimateBreatheCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Breathe")
	mr.breatheExpects = append(mr.breatheExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockPrimateBreatheCall is the typed call wrapper for Breathe.
type MockPrimateBreatheCall = gomock.Call0_0

// Eat mocks base method.
func (m *MockPrimate) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockPrimateMockRecorder) Eat(foods ...any) *MockPrimateEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockPrimateEatCall is the typed call wrapper for Eat.
type MockPrimateEatCall = gomock.Call0V_0[package_mode.Food]

// Sleep mocks base method.
func (m *MockPrimate) Sleep(duration time.Duration) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.sleepExpects, m.ctrl, m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockPrimateMockRecorder) Sleep(duration any) *MockPrimateSleepCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[time.Duration](mr.mock.ctrl.T, mr.mock, "Sleep", gomock.EnsureMatcher(duration))
	mr.sleepExpects = append(mr.sleepExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockPrimateSleepCall is the typed call wrapper for Sleep.
type MockPrimateSleepCall = gomock.Call1_0[time.Duration]

// MockCar is a mock of Car interface.
type MockCar[FuelType fuel.Fuel] struct {
	ctrl     *gomock.Controller
	recorder *MockCarMockRecorder[FuelType]
	isgomock struct{}
}

// MockCarMockRecorder is the mock recorder for MockCar.
type MockCarMockRecorder[FuelType fuel.Fuel] struct {
	mock            *MockCar[FuelType]
	brandExpects    []*gomock.Call0_1[string]
	fuelTankExpects []*gomock.Call0_1[cars.FuelTank[FuelType]]
	refuelExpects   []*gomock.Call2_1[FuelType, int, error]
}

// NewMockCar creates a new mock instance.
func NewMockCar[FuelType fuel.Fuel](ctrl *gomock.Controller) *MockCar[FuelType] {
	mock := &MockCar[FuelType]{ctrl: ctrl}
	mock.recorder = &MockCarMockRecorder[FuelType]{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCar[FuelType]) EXPECT() *MockCarMockRecorder[FuelType] {
	return m.recorder
}

// Brand mocks base method.
func (m *MockCar[FuelType]) Brand() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.brandExpects, m.ctrl, m, "Brand")
}

// Brand indicates an expected call of Brand.
func (mr *MockCarMockRecorder[FuelType]) Brand() *MockCarBrandCall[FuelType] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Brand")
	mr.brandExpects = append(mr.brandExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCarBrandCall is the typed call wrapper for Brand.
type MockCarBrandCall[FuelType fuel.Fuel] = gomock.Call0_1[string]

// FuelTank mocks base method.
func (m *MockCar[FuelType]) FuelTank() cars.FuelTank[FuelType] {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.fuelTankExpects, m.ctrl, m, "FuelTank")
}

// FuelTank indicates an expected call of FuelTank.
func (mr *MockCarMockRecorder[FuelType]) FuelTank() *MockCarFuelTankCall[FuelType] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[cars.FuelTank[FuelType]](mr.mock.ctrl.T, mr.mock, "FuelTank")
	mr.fuelTankExpects = append(mr.fuelTankExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCarFuelTankCall is the typed call wrapper for FuelTank.
type MockCarFuelTankCall[FuelType fuel.Fuel] = gomock.Call0_1[cars.FuelTank[FuelType]]

// Refuel mocks base method.
func (m *MockCar[FuelType]) Refuel(arg0 FuelType, volume int) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.refuelExpects, m.ctrl, m, "Refuel", arg0, volume)
}

// Refuel indicates an expected call of Refuel.
func (mr *MockCarMockRecorder[FuelType]) Refuel(arg0, volume any) *MockCarRefuelCall[FuelType] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[FuelType, int, error](mr.mock.ctrl.T, mr.mock, "Refuel", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(volume))
	mr.refuelExpects = append(mr.refuelExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCarRefuelCall is the typed call wrapper for Refuel.
type MockCarRefuelCall[FuelType fuel.Fuel] = gomock.Call2_1[FuelType, int, error]

// MockDriver is a mock of Driver interface.
type MockDriver[FuelType fuel.Fuel, CarType package_mode.Car[FuelType]] struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder[FuelType, CarType]
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder[FuelType fuel.Fuel, CarType package_mode.Car[FuelType]] struct {
	mock         *MockDriver[FuelType, CarType]
	driveExpects []*gomock.Call1_0[CarType]
	wroomExpects []*gomock.Call0_1[error]
}

// NewMockDriver creates a new mock instance.
func NewMockDriver[FuelType fuel.Fuel, CarType package_mode.Car[FuelType]](ctrl *gomock.Controller) *MockDriver[FuelType, CarType] {
	mock := &MockDriver[FuelType, CarType]{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder[FuelType, CarType]{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver[FuelType, CarType]) EXPECT() *MockDriverMockRecorder[FuelType, CarType] {
	return m.recorder
}

// Drive mocks base method.
func (m *MockDriver[FuelType, CarType]) Drive(car CarType) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.driveExpects, m.ctrl, m, "Drive", car)
}

// Drive indicates an expected call of Drive.
func (mr *MockDriverMockRecorder[FuelType, CarType]) Drive(car any) *MockDriverDriveCall[FuelType, CarType] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[CarType](mr.mock.ctrl.T, mr.mock, "Drive", gomock.EnsureMatcher(car))
	mr.driveExpects = append(mr.driveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDriverDriveCall is the typed call wrapper for Drive.
type MockDriverDriveCall[FuelType fuel.Fuel, CarType package_mode.Car[FuelType]] = gomock.Call1_0[CarType]

// Wroom mocks base method.
func (m *MockDriver[FuelType, CarType]) Wroom() error {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.wroomExpects, m.ctrl, m, "Wroom")
}

// Wroom indicates an expected call of Wroom.
func (mr *MockDriverMockRecorder[FuelType, CarType]) Wroom() *MockDriverWroomCall[FuelType, CarType] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[error](mr.mock.ctrl.T, mr.mock, "Wroom")
	mr.wroomExpects = append(mr.wroomExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDriverWroomCall is the typed call wrapper for Wroom.
type MockDriverWroomCall[FuelType fuel.Fuel, CarType package_mode.Car[FuelType]] = gomock.Call0_1[error]

// MockUrbanResident is a mock of UrbanResident interface.
type MockUrbanResident struct {
	ctrl     *gomock.Controller
	recorder *MockUrbanResidentMockRecorder
	isgomock struct{}
}

// MockUrbanResidentMockRecorder is the mock recorder for MockUrbanResident.
type MockUrbanResidentMockRecorder struct {
	mock                *MockUrbanResident
	breatheExpects      []*gomock.Call0_0
	doExpects           []*gomock.Call1_1[*package_mode.Work, error]
	driveExpects        []*gomock.Call1_0[cars.HyundaiSolaris]
	eatExpects          []*gomock.Call0V_0[package_mode.Food]
	livesInACityExpects []*gomock.Call0_0
	sleepExpects        []*gomock.Call1_0[time.Duration]
	wroomExpects        []*gomock.Call0_1[error]
}

// NewMockUrbanResident creates a new mock instance.
func NewMockUrbanResident(ctrl *gomock.Controller) *MockUrbanResident {
	mock := &MockUrbanResident{ctrl: ctrl}
	mock.recorder = &MockUrbanResidentMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrbanResident) EXPECT() *MockUrbanResidentMockRecorder {
	return m.recorder
}

// Breathe mocks base method.
func (m *MockUrbanResident) Breathe() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.breatheExpects, m.ctrl, m, "Breathe")
}

// Breathe indicates an expected call of Breathe.
func (mr *MockUrbanResidentMockRecorder) Breathe() *MockUrbanResidentBreatheCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Breathe")
	mr.breatheExpects = append(mr.breatheExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentBreatheCall is the typed call wrapper for Breathe.
type MockUrbanResidentBreatheCall = gomock.Call0_0

// Do mocks base method.
func (m *MockUrbanResident) Do(work *package_mode.Work) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.doExpects, m.ctrl, m, "Do", work)
}

// Do indicates an expected call of Do.
func (mr *MockUrbanResidentMockRecorder) Do(work any) *MockUrbanResidentDoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[*package_mode.Work, error](mr.mock.ctrl.T, mr.mock, "Do", gomock.EnsureMatcher(work))
	mr.doExpects = append(mr.doExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentDoCall is the typed call wrapper for Do.
type MockUrbanResidentDoCall = gomock.Call1_1[*package_mode.Work, error]

// Drive mocks base method.
func (m *MockUrbanResident) Drive(car cars.HyundaiSolaris) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.driveExpects, m.ctrl, m, "Drive", car)
}

// Drive indicates an expected call of Drive.
func (mr *MockUrbanResidentMockRecorder) Drive(car any) *MockUrbanResidentDriveCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[cars.HyundaiSolaris](mr.mock.ctrl.T, mr.mock, "Drive", gomock.EnsureMatcher(car))
	mr.driveExpects = append(mr.driveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentDriveCall is the typed call wrapper for Drive.
type MockUrbanResidentDriveCall = gomock.Call1_0[cars.HyundaiSolaris]

// Eat mocks base method.
func (m *MockUrbanResident) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockUrbanResidentMockRecorder) Eat(foods ...any) *MockUrbanResidentEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentEatCall is the typed call wrapper for Eat.
type MockUrbanResidentEatCall = gomock.Call0V_0[package_mode.Food]

// LivesInACity mocks base method.
func (m *MockUrbanResident) LivesInACity() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.livesInACityExpects, m.ctrl, m, "LivesInACity")
}

// LivesInACity indicates an expected call of LivesInACity.
func (mr *MockUrbanResidentMockRecorder) LivesInACity() *MockUrbanResidentLivesInACityCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "LivesInACity")
	mr.livesInACityExpects = append(mr.livesInACityExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentLivesInACityCall is the typed call wrapper for LivesInACity.
type MockUrbanResidentLivesInACityCall = gomock.Call0_0

// Sleep mocks base method.
func (m *MockUrbanResident) Sleep(duration time.Duration) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.sleepExpects, m.ctrl, m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockUrbanResidentMockRecorder) Sleep(duration any) *MockUrbanResidentSleepCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[time.Duration](mr.mock.ctrl.T, mr.mock, "Sleep", gomock.EnsureMatcher(duration))
	mr.sleepExpects = append(mr.sleepExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentSleepCall is the typed call wrapper for Sleep.
type MockUrbanResidentSleepCall = gomock.Call1_0[time.Duration]

// Wroom mocks base method.
func (m *MockUrbanResident) Wroom() error {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.wroomExpects, m.ctrl, m, "Wroom")
}

// Wroom indicates an expected call of Wroom.
func (mr *MockUrbanResidentMockRecorder) Wroom() *MockUrbanResidentWroomCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[error](mr.mock.ctrl.T, mr.mock, "Wroom")
	mr.wroomExpects = append(mr.wroomExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUrbanResidentWroomCall is the typed call wrapper for Wroom.
type MockUrbanResidentWroomCall = gomock.Call0_1[error]

// MockFarmer is a mock of Farmer interface.
type MockFarmer struct {
	ctrl     *gomock.Controller
	recorder *MockFarmerMockRecorder
	isgomock struct{}
}

// MockFarmerMockRecorder is the mock recorder for MockFarmer.
type MockFarmerMockRecorder struct {
	mock                   *MockFarmer
	breatheExpects         []*gomock.Call0_0
	doExpects              []*gomock.Call1_1[*package_mode.Work, error]
	driveExpects           []*gomock.Call1_0[cars.FordF150]
	eatExpects             []*gomock.Call0V_0[package_mode.Food]
	livesInAVillageExpects []*gomock.Call0_0
	sleepExpects           []*gomock.Call1_0[time.Duration]
	wroomExpects           []*gomock.Call0_1[error]
}

// NewMockFarmer creates a new mock instance.
func NewMockFarmer(ctrl *gomock.Controller) *MockFarmer {
	mock := &MockFarmer{ctrl: ctrl}
	mock.recorder = &MockFarmerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFarmer) EXPECT() *MockFarmerMockRecorder {
	return m.recorder
}

// Breathe mocks base method.
func (m *MockFarmer) Breathe() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.breatheExpects, m.ctrl, m, "Breathe")
}

// Breathe indicates an expected call of Breathe.
func (mr *MockFarmerMockRecorder) Breathe() *MockFarmerBreatheCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Breathe")
	mr.breatheExpects = append(mr.breatheExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerBreatheCall is the typed call wrapper for Breathe.
type MockFarmerBreatheCall = gomock.Call0_0

// Do mocks base method.
func (m *MockFarmer) Do(work *package_mode.Work) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.doExpects, m.ctrl, m, "Do", work)
}

// Do indicates an expected call of Do.
func (mr *MockFarmerMockRecorder) Do(work any) *MockFarmerDoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[*package_mode.Work, error](mr.mock.ctrl.T, mr.mock, "Do", gomock.EnsureMatcher(work))
	mr.doExpects = append(mr.doExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerDoCall is the typed call wrapper for Do.
type MockFarmerDoCall = gomock.Call1_1[*package_mode.Work, error]

// Drive mocks base method.
func (m *MockFarmer) Drive(car cars.FordF150) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.driveExpects, m.ctrl, m, "Drive", car)
}

// Drive indicates an expected call of Drive.
func (mr *MockFarmerMockRecorder) Drive(car any) *MockFarmerDriveCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[cars.FordF150](mr.mock.ctrl.T, mr.mock, "Drive", gomock.EnsureMatcher(car))
	mr.driveExpects = append(mr.driveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerDriveCall is the typed call wrapper for Drive.
type MockFarmerDriveCall = gomock.Call1_0[cars.FordF150]

// Eat mocks base method.
func (m *MockFarmer) Eat(foods ...package_mode.Food) {
	m.ctrl.T.Helper()
	gomock.Dispatch0V_0(&m.recorder.eatExpects, m.ctrl, m, "Eat", foods...)
}

// Eat indicates an expected call of Eat.
func (mr *MockFarmerMockRecorder) Eat(foods ...any) *MockFarmerEatCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(foods))
	for i, a := range foods {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall0V_0[package_mode.Food](mr.mock.ctrl.T, mr.mock, "Eat", varArgs)
	mr.eatExpects = append(mr.eatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerEatCall is the typed call wrapper for Eat.
type MockFarmerEatCall = gomock.Call0V_0[package_mode.Food]

// LivesInAVillage mocks base method.
func (m *MockFarmer) LivesInAVillage() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.livesInAVillageExpects, m.ctrl, m, "LivesInAVillage")
}

// LivesInAVillage indicates an expected call of LivesInAVillage.
func (mr *MockFarmerMockRecorder) LivesInAVillage() *MockFarmerLivesInAVillageCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "LivesInAVillage")
	mr.livesInAVillageExpects = append(mr.livesInAVillageExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerLivesInAVillageCall is the typed call wrapper for LivesInAVillage.
type MockFarmerLivesInAVillageCall = gomock.Call0_0

// Sleep mocks base method.
func (m *MockFarmer) Sleep(duration time.Duration) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.sleepExpects, m.ctrl, m, "Sleep", duration)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockFarmerMockRecorder) Sleep(duration any) *MockFarmerSleepCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[time.Duration](mr.mock.ctrl.T, mr.mock, "Sleep", gomock.EnsureMatcher(duration))
	mr.sleepExpects = append(mr.sleepExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerSleepCall is the typed call wrapper for Sleep.
type MockFarmerSleepCall = gomock.Call1_0[time.Duration]

// Wroom mocks base method.
func (m *MockFarmer) Wroom() error {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.wroomExpects, m.ctrl, m, "Wroom")
}

// Wroom indicates an expected call of Wroom.
func (mr *MockFarmerMockRecorder) Wroom() *MockFarmerWroomCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[error](mr.mock.ctrl.T, mr.mock, "Wroom")
	mr.wroomExpects = append(mr.wroomExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFarmerWroomCall is the typed call wrapper for Wroom.
type MockFarmerWroomCall = gomock.Call0_1[error]

// MockEarth is a mock of Earth interface.
type MockEarth struct {
	ctrl     *gomock.Controller
	recorder *MockEarthMockRecorder
	isgomock struct{}
}

// MockEarthMockRecorder is the mock recorder for MockEarth.
type MockEarthMockRecorder struct {
	mock                   *MockEarth
	addHumansExpects       []*gomock.Call1_1[package_mode.HumansCount, []package_mode.Human]
	humanPopulationExpects []*gomock.Call0_1[package_mode.HumansCount]
}

// NewMockEarth creates a new mock instance.
func NewMockEarth(ctrl *gomock.Controller) *MockEarth {
	mock := &MockEarth{ctrl: ctrl}
	mock.recorder = &MockEarthMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEarth) EXPECT() *MockEarthMockRecorder {
	return m.recorder
}

// AddHumans mocks base method.
func (m *MockEarth) AddHumans(arg0 package_mode.HumansCount) []package_mode.Human {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.addHumansExpects, m.ctrl, m, "AddHumans", arg0)
}

// AddHumans indicates an expected call of AddHumans.
func (mr *MockEarthMockRecorder) AddHumans(arg0 any) *MockEarthAddHumansCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[package_mode.HumansCount, []package_mode.Human](mr.mock.ctrl.T, mr.mock, "AddHumans", gomock.EnsureMatcher(arg0))
	mr.addHumansExpects = append(mr.addHumansExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockEarthAddHumansCall is the typed call wrapper for AddHumans.
type MockEarthAddHumansCall = gomock.Call1_1[package_mode.HumansCount, []package_mode.Human]

// HumanPopulation mocks base method.
func (m *MockEarth) HumanPopulation() package_mode.HumansCount {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.humanPopulationExpects, m.ctrl, m, "HumanPopulation")
}

// HumanPopulation indicates an expected call of HumanPopulation.
func (mr *MockEarthMockRecorder) HumanPopulation() *MockEarthHumanPopulationCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[package_mode.HumansCount](mr.mock.ctrl.T, mr.mock, "HumanPopulation")
	mr.humanPopulationExpects = append(mr.humanPopulationExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockEarthHumanPopulationCall is the typed call wrapper for HumanPopulation.
type MockEarthHumanPopulationCall = gomock.Call0_1[package_mode.HumansCount]
