// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/aux_imports_embedded_interface (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/aux_imports_embedded_interface Source
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
	faux "github.com/canonical/gomock/mockgen/internal/tests/aux_imports_embedded_interface/faux"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockSource) Error() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "Error"))
}

// Error indicates an expected call of Error.
func (mr *MockSourceMockRecorder) Error() *MockSourceErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSource)(nil).Error))
	return &MockSourceErrorCall{Call: call}
}

// MockSourceErrorCall is the typed call wrapper for Error.
type MockSourceErrorCall = gomock.Call0_1[string]

// Method mocks base method.
func (m *MockSource) Method() faux.Return {
	m.ctrl.T.Helper()
	return gomock.Invoke1[faux.Return](m.ctrl.Call(m, "Method"))
}

// Method indicates an expected call of Method.
func (mr *MockSourceMockRecorder) Method() *MockSourceMethodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Method", reflect.TypeOf((*MockSource)(nil).Method))
	return &MockSourceMethodCall{Call: call}
}

// MockSourceMethodCall is the typed call wrapper for Method.
type MockSourceMethodCall = gomock.Call0_1[faux.Return]
