// Copyright 2026 Canonical
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// gencall generates typed call wrappers for the gomock package.
// Run via: go run ./internal/gencall/main.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

const (
	maxArgs    = 12
	maxReturns = 5
)

// chainMethod describes a chaining method on FinalizedCallN/CallN_M.
type chainMethod struct {
	name   string
	params string
	args   string
}

// chainMethods lists all ordering/cardinality chain methods.
var chainMethods = []chainMethod{
	{"AnyTimes", "", ""},
	{"MinTimes", "n int", "n"},
	{"MaxTimes", "n int", "n"},
	{"Times", "n int", "n"},
	{"After", "preReq CallHolder", "preReq.getCall()"},
}

func main() {
	var buf bytes.Buffer
	buf.WriteString(
		"// Code generated by internal/gencall/main.go;" +
			" DO NOT EDIT.\n\npackage gomock\n",
	)
	for n := 0; n <= maxArgs; n++ {
		writeFinalizedCall(&buf, n)
	}
	for n := 0; n <= maxArgs; n++ {
		for m := 0; m <= maxReturns; m++ {
			writeCallType(&buf, n, m)
		}
	}
	for n := 0; n <= maxArgs; n++ {
		for m := 0; m <= maxReturns; m++ {
			writeDispatch(&buf, n, m)
		}
	}
	for n := 0; n <= maxArgs; n++ {
		writeFinalizedCallV(&buf, n)
	}
	for n := 0; n <= maxArgs; n++ {
		for m := 0; m <= maxReturns; m++ {
			writeCallTypeV(&buf, n, m)
		}
	}
	for n := 0; n <= maxArgs; n++ {
		for m := 0; m <= maxReturns; m++ {
			writeDispatchV(&buf, n, m)
		}
	}
	for m := 1; m <= maxReturns; m++ {
		writeInvoke(&buf, m)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf(
			"format: %v\n---\n%s", err, buf.Bytes(),
		)
	}
	if err := os.WriteFile("typed_calls.go", src, 0o644); err != nil {
		log.Fatalf("write: %v", err)
	}
}

// finalName returns e.g. "FinalizedCall2".
func finalName(n int) string {
	return fmt.Sprintf("FinalizedCall%d", n)
}

// finalTypeParams returns "[A1, A2 any]" or "" for n=0.
func finalTypeParams(n int) string {
	if n == 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	return "[" + strings.Join(parts, ", ") + " any]"
}

// finalTypeArgs returns "[A1, A2]" or "" for n=0.
func finalTypeArgs(n int) string {
	if n == 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// finalSelf returns e.g. "*FinalizedCall2[A1, A2]".
func finalSelf(n int) string {
	return "*" + finalName(n) + finalTypeArgs(n)
}

// callTypeName returns e.g. "Call1_2".
func callTypeName(n, m int) string {
	return fmt.Sprintf("Call%d_%d", n, m)
}

// allTypeParams returns "[A1, R1, R2 any]" or "" for n=m=0.
func allTypeParams(n, m int) string {
	if n == 0 && m == 0 {
		return ""
	}
	parts := make([]string, 0, n+m)
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + " any]"
}

// allTypeArgs returns "[A1, R1, R2]" or "" for n=m=0.
func allTypeArgs(n, m int) string {
	if n == 0 && m == 0 {
		return ""
	}
	parts := make([]string, 0, n+m)
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// callSelf returns e.g. "*Call1_2[A1, R1, R2]".
func callSelf(n, m int) string {
	return "*" + callTypeName(n, m) + allTypeArgs(n, m)
}

// doFuncType returns "func()" or "func(A1, A2)".
func doFuncType(n int) string {
	if n == 0 {
		return "func()"
	}
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	return "func(" + strings.Join(parts, ", ") + ")"
}

// retSignature returns "", " R1", or " (R1, R2, R3)".
func retSignature(m int) string {
	switch m {
	case 0:
		return ""
	case 1:
		return " R1"
	default:
		parts := make([]string, m)
		for i := range parts {
			parts[i] = fmt.Sprintf("R%d", i+1)
		}
		return " (" + strings.Join(parts, ", ") + ")"
	}
}

// doAndReturnFuncType returns e.g. "func(A1) (R1, R2)".
func doAndReturnFuncType(n, m int) string {
	return doFuncType(n) + retSignature(m)
}

// argParams returns "a1 A1, a2 A2".
func argParams(n int) string {
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("a%d A%d", i+1, i+1)
	}
	return strings.Join(parts, ", ")
}

// argList returns "a1, a2, a3".
func argList(n int) string {
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// retValList returns "*e.retV1, *e.retV2".
func retValList(m int) string {
	parts := make([]string, m)
	for i := range parts {
		parts[i] = fmt.Sprintf("*e.retV%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// zeroReturnList returns "zero1, zero2".
func zeroReturnList(m int) string {
	parts := make([]string, m)
	for i := range parts {
		parts[i] = fmt.Sprintf("zero%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// fatalfStmt builds the ctrl.T.Fatalf(...) statement for n args.
func fatalfStmt(n int) string {
	fmts := make([]string, n)
	for i := range fmts {
		fmts[i] = "%v"
	}
	format := "Unexpected call to %T.%v(" +
		strings.Join(fmts, ", ") + ") at %s"
	var args strings.Builder
	args.WriteString("receiver, method")
	for i := 1; i <= n; i++ {
		args.WriteString(fmt.Sprintf(", a%d", i))
	}
	args.WriteString(", origin")
	return fmt.Sprintf(
		`ctrl.T.Fatalf("%s", %s)`, format, args.String(),
	)
}

// finalVName returns e.g. "FinalizedCall2V".
func finalVName(n int) string {
	return fmt.Sprintf("FinalizedCall%dV", n)
}

// finalVTypeParams returns e.g. "[A1, A2, VA any]" for n=2.
func finalVTypeParams(n int) string {
	parts := make([]string, n+1)
	for i := range n {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	parts[n] = "VA"
	return "[" + strings.Join(parts, ", ") + " any]"
}

// finalVTypeArgs returns e.g. "[A1, A2, VA]" for n=2.
func finalVTypeArgs(n int) string {
	parts := make([]string, n+1)
	for i := range n {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	parts[n] = "VA"
	return "[" + strings.Join(parts, ", ") + "]"
}

// finalVSelf returns e.g. "*FinalizedCall2V[A1, A2, VA]".
func finalVSelf(n int) string {
	return "*" + finalVName(n) + finalVTypeArgs(n)
}

// callVTypeName returns e.g. "Call2V_3".
func callVTypeName(n, m int) string {
	return fmt.Sprintf("Call%dV_%d", n, m)
}

// allVTypeParams returns e.g. "[A1, A2, VA, R1, R2 any]" for n=2, m=2.
func allVTypeParams(n, m int) string {
	parts := make([]string, 0, n+1+m)
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	parts = append(parts, "VA")
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + " any]"
}

// allVTypeArgs returns e.g. "[A1, A2, VA, R1, R2]" for n=2, m=2.
func allVTypeArgs(n, m int) string {
	parts := make([]string, 0, n+1+m)
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	parts = append(parts, "VA")
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// callVSelf returns e.g. "*Call2V_3[A1, A2, VA, R1, R2, R3]".
func callVSelf(n, m int) string {
	return "*" + callVTypeName(n, m) + allVTypeArgs(n, m)
}

// doVFuncType returns e.g. "func(A1, A2, ...VA)" or
// "func(...VA)" for n=0.
func doVFuncType(n int) string {
	if n == 0 {
		return "func(...VA)"
	}
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("A%d", i+1)
	}
	return "func(" + strings.Join(parts, ", ") + ", ...VA)"
}

// doAndReturnVFuncType returns e.g. "func(A1, ...VA) (R1, R2)".
func doAndReturnVFuncType(n, m int) string {
	return doVFuncType(n) + retSignature(m)
}

// fatalfVStmt builds the ctrl.T.Fatalf statement for variadic
// dispatch with n fixed args.
func fatalfVStmt(n int) string {
	fmts := make([]string, n+1)
	for i := range n {
		fmts[i] = "%v"
	}
	fmts[n] = "%v"
	format := "Unexpected call to %T.%v(" +
		strings.Join(fmts, ", ") + ") at %s"
	var args strings.Builder
	args.WriteString("receiver, method")
	for i := 1; i <= n; i++ {
		args.WriteString(fmt.Sprintf(", a%d", i))
	}
	args.WriteString(", va, origin")
	return fmt.Sprintf(`ctrl.T.Fatalf("%s", %s)`, format, args.String())
}

// writeFinalizedCall writes the FinalizedCallN type and its methods.
func writeFinalizedCall(buf *bytes.Buffer, n int) {
	name := finalName(n)
	tp := finalTypeParams(n)
	self := finalSelf(n)
	doFunc := doFuncType(n)

	fmt.Fprintf(buf,
		"\n// %s is the finalized call wrapper for %d-arg methods.\n"+
			"// It is returned by Return and DoAndReturn.\n"+
			"type %s%s struct {\n"+
			"\tCall     *Call\n"+
			"\treceiver any\n"+
			"\tmethod   string\n"+
			"\torigin   string\n"+
			"\tdoFns    []%s\n"+
			"}\n",
		name, n, name, tp, doFunc,
	)

	// getCall implements CallHolder.
	fmt.Fprintf(buf,
		"\nfunc (c %s) getCall() *Call { return c.Call }\n",
		self,
	)

	// String implements fmt.Stringer.
	fmt.Fprintf(buf,
		"\nfunc (c %s) String() string {\n"+
			"\treturn formatCallString(c.receiver, c.method, nil, c.origin)\n"+
			"}\n",
		self,
	)

	// Do appends to doFns and returns the receiver.
	fmt.Fprintf(buf,
		"\n// Do adds f to the functions called when matched.\n"+
			"func (c %s) Do(f %s) %s {\n"+
			"\tc.doFns = append(c.doFns, f)\n"+
			"\treturn c\n"+
			"}\n",
		self, doFunc, self,
	)

	for _, cm := range chainMethods {
		writeChainMethod(buf, self, cm.name, cm.params, cm.args)
	}
}

// writeFinalizedCallV writes the FinalizedCallNV type and its methods.
func writeFinalizedCallV(buf *bytes.Buffer, n int) {
	name := finalVName(n)
	tp := finalVTypeParams(n)
	self := finalVSelf(n)
	doFunc := doVFuncType(n)

	fmt.Fprintf(buf,
		"\n// %s is the finalized call wrapper"+
			" for %d-arg variadic methods.\n"+
			"// It is returned by Return and DoAndReturn.\n"+
			"type %s%s struct {\n"+
			"\tCall     *Call\n"+
			"\treceiver any\n"+
			"\tmethod   string\n"+
			"\torigin   string\n"+
			"\tdoFns    []%s\n"+
			"}\n",
		name, n, name, tp, doFunc,
	)

	fmt.Fprintf(buf,
		"\nfunc (c %s) getCall() *Call { return c.Call }\n",
		self,
	)

	// String implements fmt.Stringer.
	fmt.Fprintf(buf,
		"\nfunc (c %s) String() string {\n"+
			"\treturn formatCallString(c.receiver, c.method, nil, c.origin)\n"+
			"}\n",
		self,
	)

	fmt.Fprintf(buf,
		"\n// Do adds f to the functions called when matched.\n"+
			"func (c %s) Do(f %s) %s {\n"+
			"\tc.doFns = append(c.doFns, f)\n"+
			"\treturn c\n"+
			"}\n",
		self, doFunc, self,
	)

	for _, cm := range chainMethods {
		writeChainMethod(buf, self, cm.name, cm.params, cm.args)
	}
}

// writeChainMethod writes a chain method that delegates to c.call.
func writeChainMethod(
	buf *bytes.Buffer,
	self, name, params, args string,
) {
	fmt.Fprintf(buf,
		"\nfunc (c %s) %s(%s) %s {\n"+
			"\tc.Call.%s(%s)\n"+
			"\treturn c\n"+
			"}\n",
		self, name, params, self, name, args,
	)
}

// writeCallType writes the CallN_M struct, constructor, and methods.
func writeCallType(buf *bytes.Buffer, n, m int) {
	name := callTypeName(n, m)
	tp := allTypeParams(n, m)
	self := callSelf(n, m)
	finName := finalName(n)
	finArgs := finalTypeArgs(n)
	finSelf := finalSelf(n)
	doFunc := doFuncType(n)

	// Struct definition.
	fmt.Fprintf(buf,
		"\n// %s wraps %s for a method with %d args"+
			" and %d return values.\n"+
			"type %s%s struct {\n"+
			"\t%s%s\n",
		name, finName, n, m,
		name, tp,
		finName, finArgs,
	)
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\tm%d Matcher\n", i)
	}
	if m > 0 {
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tretV%d *R%d\n", i, i)
		}
		fmt.Fprintf(buf,
			"\tdoReturnFn %s\n",
			doAndReturnFuncType(n, m),
		)
	}
	buf.WriteString("}\n")

	// Constructor.
	var ctorExtra string
	if n > 0 {
		mps := make([]string, n)
		for i := range mps {
			mps[i] = fmt.Sprintf("m%d Matcher", i+1)
		}
		ctorExtra = ", " + strings.Join(mps, ", ")
	}
	ctorTA := allTypeArgs(n, m)
	// String implements fmt.Stringer.
	var matchersArg string
	if n == 0 {
		matchersArg = "nil"
	} else {
		parts := make([]string, n)
		for i := range parts {
			parts[i] = fmt.Sprintf("c.m%d", i+1)
		}
		matchersArg = "[]Matcher{" + strings.Join(parts, ", ") + "}"
	}
	fmt.Fprintf(buf,
		"\nfunc (c %s) String() string {\n"+
			"\treturn formatCallString(c.receiver, c.method, %s, c.origin)\n"+
			"}\n",
		self, matchersArg,
	)

	fmt.Fprintf(buf,
		"\n// NewCall%d_%d creates a new %s expectation.\n"+
			"func NewCall%d_%d%s("+
			"t TestHelper, receiver any, method string%s"+
			") *%s%s {\n"+
			"\tt.Helper()\n"+
			"\tc := &%s%s{\n"+
			"\t\t%s: %s%s{\n"+
			"\t\t\treceiver: receiver,\n"+
			"\t\t\tmethod:   method,\n"+
			"\t\t\torigin:   callerInfo(2),\n"+
			"\t\t},\n",
		n, m, name,
		n, m, tp, ctorExtra,
		name, ctorTA,
		name, ctorTA,
		finName, finName, finArgs,
	)
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\t\tm%d: m%d,\n", i, i)
	}
	fmt.Fprintf(buf,
		"\t}\n"+
			"\tc.%s.Call = newCall(t, c)\n"+
			"\treturn c\n"+
			"}\n",
		finName,
	)

	// Do override — returns *CallN_M to preserve the specific type.
	fmt.Fprintf(buf,
		"\nfunc (c %s) Do(f %s) %s {\n"+
			"\tc.doFns = append(c.doFns, f)\n"+
			"\treturn c\n"+
			"}\n",
		self, doFunc, self,
	)

	// Return and DoAndReturn are only present when m > 0.
	if m > 0 {
		retParams := make([]string, m)
		for i := range retParams {
			retParams[i] = fmt.Sprintf("r%d R%d", i+1, i+1)
		}
		fmt.Fprintf(buf,
			"\nfunc (c %s) Return(%s) %s {\n",
			self, strings.Join(retParams, ", "), finSelf,
		)
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tc.retV%d = &r%d\n", i, i)
		}
		fmt.Fprintf(buf, "\treturn &c.%s\n}\n", finName)

		drFunc := doAndReturnFuncType(n, m)
		fmt.Fprintf(buf,
			"\nfunc (c %s) DoAndReturn(f %s) %s {\n"+
				"\tc.doReturnFn = f\n"+
				"\treturn &c.%s\n"+
				"}\n",
			self, drFunc, finSelf, finName,
		)
	}

	// Chain method overrides — return *CallN_M.
	for _, cm := range chainMethods {
		writeChainMethod(buf, self, cm.name, cm.params, cm.args)
	}
}

// writeCallTypeV writes the CallNV_M struct, constructor, and methods.
func writeCallTypeV(buf *bytes.Buffer, n, m int) {
	name := callVTypeName(n, m)
	tp := allVTypeParams(n, m)
	self := callVSelf(n, m)
	finName := finalVName(n)
	finArgs := finalVTypeArgs(n)
	finSelf := finalVSelf(n)
	doFunc := doVFuncType(n)

	// Struct definition.
	fmt.Fprintf(buf,
		"\n// %s wraps %s for a variadic method with %d fixed"+
			" args and %d return values.\n"+
			"type %s%s struct {\n"+
			"\t%s%s\n",
		name, finName, n, m,
		name, tp,
		finName, finArgs,
	)
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\tm%d Matcher\n", i)
	}
	fmt.Fprintf(buf, "\tvarArgs []Matcher\n")
	if m > 0 {
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tretV%d *R%d\n", i, i)
		}
		fmt.Fprintf(buf,
			"\tdoReturnFn %s\n",
			doAndReturnVFuncType(n, m),
		)
	}
	buf.WriteString("}\n")

	// Constructor: takes fixed matchers then varArgs []Matcher.
	mps := make([]string, 0, n+1)
	for i := 1; i <= n; i++ {
		mps = append(mps, fmt.Sprintf("m%d Matcher", i))
	}
	mps = append(mps, "varArgs []Matcher")
	ctorExtra := ", " + strings.Join(mps, ", ")
	ctorTA := allVTypeArgs(n, m)
	// String implements fmt.Stringer.
	var matchersArg string
	if n == 0 {
		matchersArg = "c.varArgs"
	} else {
		parts := make([]string, n)
		for i := range parts {
			parts[i] = fmt.Sprintf("c.m%d", i+1)
		}
		matchersArg = "append([]Matcher{" + strings.Join(parts, ", ") + "}, c.varArgs...)"
	}
	fmt.Fprintf(buf,
		"\nfunc (c %s) String() string {\n"+
			"\treturn formatCallString(c.receiver, c.method, %s, c.origin)\n"+
			"}\n",
		self, matchersArg,
	)

	fmt.Fprintf(buf,
		"\n// NewCall%dV_%d creates a new %s expectation.\n"+
			"func NewCall%dV_%d%s("+
			"t TestHelper, receiver any, method string%s"+
			") *%s%s {\n"+
			"\tt.Helper()\n"+
			"\tc := &%s%s{\n"+
			"\t\t%s: %s%s{\n"+
			"\t\t\treceiver: receiver,\n"+
			"\t\t\tmethod:   method,\n"+
			"\t\t\torigin:   callerInfo(2),\n"+
			"\t\t},\n",
		n, m, name,
		n, m, tp, ctorExtra,
		name, ctorTA,
		name, ctorTA,
		finName, finName, finArgs,
	)
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf, "\t\tm%d: m%d,\n", i, i)
	}
	fmt.Fprintf(buf,
		"\t\tvarArgs: varArgs,\n"+
			"\t}\n"+
			"\tc.%s.Call = newCall(t, c)\n"+
			"\treturn c\n"+
			"}\n",
		finName,
	)

	// Do override — returns *CallNV_M to preserve the specific type.
	fmt.Fprintf(buf,
		"\nfunc (c %s) Do(f %s) %s {\n"+
			"\tc.doFns = append(c.doFns, f)\n"+
			"\treturn c\n"+
			"}\n",
		self, doFunc, self,
	)

	// Return and DoAndReturn only when m > 0.
	if m > 0 {
		retParams := make([]string, m)
		for i := range retParams {
			retParams[i] = fmt.Sprintf("r%d R%d", i+1, i+1)
		}
		fmt.Fprintf(buf,
			"\nfunc (c %s) Return(%s) %s {\n",
			self, strings.Join(retParams, ", "), finSelf,
		)
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tc.retV%d = &r%d\n", i, i)
		}
		fmt.Fprintf(buf, "\treturn &c.%s\n}\n", finName)

		drFunc := doAndReturnVFuncType(n, m)
		fmt.Fprintf(buf,
			"\nfunc (c %s) DoAndReturn(f %s) %s {\n"+
				"\tc.doReturnFn = f\n"+
				"\treturn &c.%s\n"+
				"}\n",
			self, drFunc, finSelf, finName,
		)
	}

	// Chain method overrides — return *CallNV_M.
	for _, cm := range chainMethods {
		writeChainMethod(buf, self, cm.name, cm.params, cm.args)
	}
}

// writeDispatch writes the DispatchN_M free function.
func writeDispatch(buf *bytes.Buffer, n, m int) {
	name := callTypeName(n, m)
	tp := allTypeParams(n, m)
	typeInst := name + allTypeArgs(n, m)
	retSig := retSignature(m)
	args := argList(n)

	params := "expects *[]*" + typeInst +
		", ctrl *Controller, receiver any, method string"
	if n > 0 {
		params += ", " + argParams(n)
	}

	fmt.Fprintf(buf,
		"\n// Dispatch%d_%d dispatches a typed call"+
			" to matching expectations.\n"+
			"func Dispatch%d_%d%s(%s)%s {\n",
		n, m, n, m, tp, params, retSig,
	)

	buf.WriteString("\tctrl.T.Helper()\n")
	buf.WriteString("\tctrl.mu.Lock()\n")

	// When overridable, iterate in reverse so the most recently
	// registered expectation takes precedence (last-write-wins).
	buf.WriteString("\tstart, step := 0, 1\n")
	buf.WriteString("\tif ctrl.overridable {\n")
	buf.WriteString("\t\tstart, step = len(*expects)-1, -1\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor idx := start; idx >= 0 && idx < len(*expects); idx += step {\n")
	buf.WriteString("\t\ti, e := idx, (*expects)[idx]\n")

	// Argument matcher checks.
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf,
			"\t\tif !e.m%d.Matches(a%d) {\n"+
				"\t\t\tcontinue\n"+
				"\t\t}\n",
			i, i,
		)
	}

	// Skip expectations that are already exhausted (e.g. Times(0)).
	buf.WriteString("\t\tif e.Call.exhausted() {\n")
	buf.WriteString("\t\t\tcontinue\n")
	buf.WriteString("\t\t}\n")

	// Prerequisite check.
	buf.WriteString("\t\tprereqOK := true\n")
	buf.WriteString("\t\tfor _, p := range e.Call.preReqs {\n")
	buf.WriteString("\t\t\tif !p.satisfied() {\n")
	buf.WriteString("\t\t\t\tprereqOK = false\n")
	buf.WriteString("\t\t\t\tbreak\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif !prereqOK {\n\t\t\tcontinue\n\t\t}\n")

	// Match found — update call state.
	// When overridable, mark all earlier expectations as no longer
	// required so Finish() does not complain about them.
	buf.WriteString("\t\tif ctrl.overridable {\n")
	buf.WriteString("\t\t\tfor j := 0; j < i; j++ {\n")
	buf.WriteString("\t\t\t\t(*expects)[j].Call.minCalls = 0\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\te.Call.numCalls++\n")
	buf.WriteString("\t\tpreReqs := e.Call.dropPrereqs()\n")
	buf.WriteString("\t\tfor _, p := range preReqs {\n")
	buf.WriteString("\t\t\tctrl.removeCall(p)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif e.Call.exhausted() {\n")
	buf.WriteString(
		"\t\t\t*expects = append(" +
			"(*expects)[:i], (*expects)[i+1:]...)\n",
	)
	buf.WriteString("\t\t\tctrl.removeCall(e.Call)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tctrl.mu.Unlock()\n")

	// Run doFns.
	if n == 0 {
		buf.WriteString("\t\tfor _, f := range e.doFns {\n")
		buf.WriteString("\t\t\tf()\n")
		buf.WriteString("\t\t}\n")
	} else {
		fmt.Fprintf(buf,
			"\t\tfor _, f := range e.doFns {\n"+
				"\t\t\tf(%s)\n"+
				"\t\t}\n",
			args,
		)
	}

	// Return values.
	if m == 0 {
		buf.WriteString("\t\treturn\n")
	} else {
		if n == 0 {
			buf.WriteString(
				"\t\tif e.doReturnFn != nil {\n" +
					"\t\t\treturn e.doReturnFn()\n" +
					"\t\t}\n",
			)
		} else {
			fmt.Fprintf(buf,
				"\t\tif e.doReturnFn != nil {\n"+
					"\t\t\treturn e.doReturnFn(%s)\n"+
					"\t\t}\n",
				args,
			)
		}
		fmt.Fprintf(buf,
			"\t\tif e.retV1 != nil {\n"+
				"\t\t\treturn %s\n"+
				"\t\t}\n",
			retValList(m),
		)
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf,
				"\t\tvar zero%d R%d\n", i, i,
			)
		}
		fmt.Fprintf(buf,
			"\t\treturn %s\n", zeroReturnList(m),
		)
	}

	buf.WriteString("\t}\n")

	// No match — Fatalf.
	buf.WriteString("\torigin := callerInfo(2)\n")
	buf.WriteString("\tctrl.mu.Unlock()\n")
	buf.WriteString("\t" + fatalfStmt(n) + "\n")

	// Unreachable zero returns satisfy the compiler.
	if m > 0 {
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tvar zero%d R%d\n", i, i)
		}
		fmt.Fprintf(buf,
			"\treturn %s\n", zeroReturnList(m),
		)
	}

	buf.WriteString("}\n")
}

// writeDispatchV writes the DispatchNV_M free function.
func writeDispatchV(buf *bytes.Buffer, n, m int) {
	name := callVTypeName(n, m)
	tp := allVTypeParams(n, m)
	typeInst := name + allVTypeArgs(n, m)
	retSig := retSignature(m)

	params := "expects *[]*" + typeInst +
		", ctrl *Controller, receiver any, method string"
	if n > 0 {
		params += ", " + argParams(n)
	}
	params += ", va ...VA"

	fmt.Fprintf(buf,
		"\n// Dispatch%dV_%d dispatches a typed variadic call"+
			" to matching expectations.\n"+
			"func Dispatch%dV_%d%s(%s)%s {\n",
		n, m, n, m, tp, params, retSig,
	)

	buf.WriteString("\tctrl.T.Helper()\n")
	buf.WriteString("\tctrl.mu.Lock()\n")
	buf.WriteString("\tstart, step := 0, 1\n")
	buf.WriteString("\tif ctrl.overridable {\n")
	buf.WriteString("\t\tstart, step = len(*expects)-1, -1\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor idx := start; idx >= 0 && idx < len(*expects); idx += step {\n")
	buf.WriteString("\t\ti, e := idx, (*expects)[idx]\n")

	// Fixed arg matcher checks.
	for i := 1; i <= n; i++ {
		fmt.Fprintf(buf,
			"\t\tif !e.m%d.Matches(a%d) {\n"+
				"\t\t\tcontinue\n"+
				"\t\t}\n",
			i, i,
		)
	}

	// Variadic matching semantics (matching old gomock behaviour):
	//   - exactly one registered matcher, exactly one actual arg:
	//     apply the matcher to that single element.
	//   - exactly one registered matcher, any other count:
	//     apply the matcher to the whole va slice.
	//   - any other count: require len(va)==len(varArgs) then
	//     match element-by-element.
	buf.WriteString("\t\tif len(e.varArgs) == 1 {\n")
	buf.WriteString("\t\t\tif len(va) == 1 {\n")
	buf.WriteString("\t\t\t\tif !e.varArgs[0].Matches(va[0]) {\n")
	buf.WriteString("\t\t\t\t\tcontinue\n")
	buf.WriteString("\t\t\t\t}\n")
	buf.WriteString("\t\t\t} else if !e.varArgs[0].Matches(va) {\n")
	buf.WriteString("\t\t\t\tcontinue\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t} else {\n")
	buf.WriteString("\t\t\tif len(e.varArgs) != len(va) {\n")
	buf.WriteString("\t\t\t\tcontinue\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t\tvarMatch := true\n")
	buf.WriteString("\t\t\tfor j, vm := range e.varArgs {\n")
	buf.WriteString("\t\t\t\tif !vm.Matches(va[j]) {\n")
	buf.WriteString("\t\t\t\t\tvarMatch = false\n")
	buf.WriteString("\t\t\t\t\tbreak\n")
	buf.WriteString("\t\t\t\t}\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t\tif !varMatch {\n\t\t\t\tcontinue\n\t\t\t}\n")
	buf.WriteString("\t\t}\n")

	// Skip exhausted expectations.
	buf.WriteString("\t\tif e.Call.exhausted() {\n")
	buf.WriteString("\t\t\tcontinue\n")
	buf.WriteString("\t\t}\n")

	// Prerequisite check.
	buf.WriteString("\t\tprereqOK := true\n")
	buf.WriteString("\t\tfor _, p := range e.Call.preReqs {\n")
	buf.WriteString("\t\t\tif !p.satisfied() {\n")
	buf.WriteString("\t\t\t\tprereqOK = false\n")
	buf.WriteString("\t\t\t\tbreak\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif !prereqOK {\n\t\t\tcontinue\n\t\t}\n")

	// Match found — update state.
	buf.WriteString("\t\tif ctrl.overridable {\n")
	buf.WriteString("\t\t\tfor j := 0; j < i; j++ {\n")
	buf.WriteString("\t\t\t\t(*expects)[j].Call.minCalls = 0\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\te.Call.numCalls++\n")
	buf.WriteString("\t\tpreReqs := e.Call.dropPrereqs()\n")
	buf.WriteString("\t\tfor _, p := range preReqs {\n")
	buf.WriteString("\t\t\tctrl.removeCall(p)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif e.Call.exhausted() {\n")
	buf.WriteString(
		"\t\t\t*expects = append(" +
			"(*expects)[:i], (*expects)[i+1:]...)\n",
	)
	buf.WriteString("\t\t\tctrl.removeCall(e.Call)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tctrl.mu.Unlock()\n")

	// Run doFns with variadic spread.
	var doCallArgs string
	if n == 0 {
		doCallArgs = "va..."
	} else {
		doCallArgs = argList(n) + ", va..."
	}
	fmt.Fprintf(buf,
		"\t\tfor _, f := range e.doFns {\n"+
			"\t\t\tf(%s)\n"+
			"\t\t}\n",
		doCallArgs,
	)

	// Return values.
	if m == 0 {
		buf.WriteString("\t\treturn\n")
	} else {
		var doReturnArgs string
		if n == 0 {
			doReturnArgs = "va..."
		} else {
			doReturnArgs = argList(n) + ", va..."
		}
		fmt.Fprintf(buf,
			"\t\tif e.doReturnFn != nil {\n"+
				"\t\t\treturn e.doReturnFn(%s)\n"+
				"\t\t}\n",
			doReturnArgs,
		)
		fmt.Fprintf(buf,
			"\t\tif e.retV1 != nil {\n"+
				"\t\t\treturn %s\n"+
				"\t\t}\n",
			retValList(m),
		)
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\t\tvar zero%d R%d\n", i, i)
		}
		fmt.Fprintf(buf, "\t\treturn %s\n", zeroReturnList(m))
	}

	buf.WriteString("\t}\n")

	// No match — Fatalf.
	buf.WriteString("\torigin := callerInfo(2)\n")
	buf.WriteString("\tctrl.mu.Unlock()\n")
	buf.WriteString("\t" + fatalfVStmt(n) + "\n")

	if m > 0 {
		for i := 1; i <= m; i++ {
			fmt.Fprintf(buf, "\tvar zero%d R%d\n", i, i)
		}
		fmt.Fprintf(buf, "\treturn %s\n", zeroReturnList(m))
	}

	buf.WriteString("}\n")
}

// writeInvoke writes an InvokeM helper that unpacks []any results.
func writeInvoke(buf *bytes.Buffer, m int) {
	parts := make([]string, m)
	for i := range parts {
		parts[i] = fmt.Sprintf("R%d", i+1)
	}
	tp := "[" + strings.Join(parts, ", ") + " any]"
	retTuple := strings.Join(parts, ", ")

	fmt.Fprintf(buf,
		"\n// Invoke%d unpacks %d typed return value(s)"+
			" from a []any result.\n"+
			"func Invoke%d%s(ret []any) (%s) {\n",
		m, m, m, tp, retTuple,
	)
	retList := make([]string, m)
	for i := 1; i <= m; i++ {
		fmt.Fprintf(buf,
			"\tr%d, _ := ret[%d].(R%d)\n", i, i-1, i,
		)
		retList[i-1] = fmt.Sprintf("r%d", i)
	}
	fmt.Fprintf(buf,
		"\treturn %s\n}\n",
		strings.Join(retList, ", "),
	)
}
