// Copyright 2026 Canonical
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// gencall generates typed call wrappers for the gomock package.
// Run via: go generate ./gomock
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

// maxArgs is the maximum number of input arguments supported.
const maxArgs = 8

// maxReturns is the maximum number of return values supported.
const maxReturns = 5

func main() {
	var buf bytes.Buffer

	buf.WriteString(`// Code generated by internal/gencall/main.go; DO NOT EDIT.

package gomock
`)

	for n := 0; n <= maxArgs; n++ {
		for m := 0; m <= maxReturns; m++ {
			writeCallType(&buf, n, m)
		}
	}
	for m := 1; m <= maxReturns; m++ {
		writeInvoke(&buf, m)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format: %v\n---\n%s", err, buf.Bytes())
	}
	if err := os.WriteFile("typed_calls.go", src, 0o644); err != nil {
		log.Fatalf("write: %v", err)
	}
}

// typeName returns the type name, e.g. "Call2_4".
func typeName(n, m int) string {
	return fmt.Sprintf("Call%d_%d", n, m)
}

// typeParams returns "[A1, A2, R1, R2 any]" or "" when both n and m are 0.
func typeParams(n, m int) string {
	if n == 0 && m == 0 {
		return ""
	}
	var parts []string
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + " any]"
}

// typeArgs returns "[A1, A2, R1, R2]" (without constraints).
func typeArgs(n, m int) string {
	if n == 0 && m == 0 {
		return ""
	}
	var parts []string
	for i := 1; i <= n; i++ {
		parts = append(parts, fmt.Sprintf("A%d", i))
	}
	for i := 1; i <= m; i++ {
		parts = append(parts, fmt.Sprintf("R%d", i))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// selfType returns e.g. "*Call2_4[A1, A2, R1, R2]".
func selfType(n, m int) string {
	return "*" + typeName(n, m) + typeArgs(n, m)
}

// argCount returns a human-readable count description.
func argCount(n int) string {
	switch n {
	case 0:
		return "0 arguments"
	case 1:
		return "1 argument"
	default:
		return fmt.Sprintf("%d arguments", n)
	}
}

// retCount returns a human-readable return count description.
func retCount(m int) string {
	switch m {
	case 0:
		return "0 return values"
	case 1:
		return "1 return value"
	default:
		return fmt.Sprintf("%d return values", m)
	}
}

func writeCallType(buf *bytes.Buffer, n, m int) {
	name := typeName(n, m)
	tp := typeParams(n, m)
	self := selfType(n, m)

	fmt.Fprintf(buf, "\n// %s wraps *Call for a method with %s and %s.\n",
		name, argCount(n), retCount(m))
	fmt.Fprintf(buf, "type %s%s struct {\n\t*Call\n}\n", name, tp)

	// Return method (only when there are return values).
	if m > 0 {
		var retParams, retArgs []string
		for i := 1; i <= m; i++ {
			retParams = append(retParams, fmt.Sprintf("r%d R%d", i, i))
			retArgs = append(retArgs, fmt.Sprintf("r%d", i))
		}
		fmt.Fprintf(buf,
			"\n// Return sets the values to be returned by this call.\n"+
				"func (c %s) Return(%s) %s {\n"+
				"\tc.Call = c.Call.Return(%s)\n"+
				"\treturn c\n}\n",
			self,
			strings.Join(retParams, ", "),
			self,
			strings.Join(retArgs, ", "),
		)
	}

	// Do method.
	var doArgs []string
	for i := 1; i <= n; i++ {
		doArgs = append(doArgs, fmt.Sprintf("A%d", i))
	}
	doFunc := "func(" + strings.Join(doArgs, ", ") + ")"
	fmt.Fprintf(buf,
		"\n// Do sets the action to run when the call is matched.\n"+
			"// Return values from f are ignored; use DoAndReturn to use them.\n"+
			"func (c %s) Do(f %s) %s {\n"+
			"\tc.Call = c.Call.Do(f)\n"+
			"\treturn c\n}\n",
		self, doFunc, self,
	)

	// DoAndReturn method.
	var doReturnTypes []string
	for i := 1; i <= m; i++ {
		doReturnTypes = append(doReturnTypes, fmt.Sprintf("R%d", i))
	}
	var doReturnStr string
	switch len(doReturnTypes) {
	case 0:
		doReturnStr = ""
	case 1:
		doReturnStr = " " + doReturnTypes[0]
	default:
		doReturnStr = " (" + strings.Join(doReturnTypes, ", ") + ")"
	}
	doAndReturnFunc := "func(" + strings.Join(doArgs, ", ") + ")" + doReturnStr
	fmt.Fprintf(buf,
		"\n// DoAndReturn sets the action to run when the call is matched.\n"+
			"// The function's return values are used as the mock's return values.\n"+
			"func (c %s) DoAndReturn(f %s) %s {\n"+
			"\tc.Call = c.Call.DoAndReturn(f)\n"+
			"\treturn c\n}\n",
		self, doAndReturnFunc, self,
	)

	// Chaining methods that preserve the typed wrapper.
	writeChainMethod(buf, self, "AnyTimes",
		"", "",
		"AnyTimes allows the expectation to be called 0 or more times.")
	writeChainMethod(buf, self, "MinTimes",
		"n int", "n",
		"MinTimes requires the call to occur at least n times.")
	writeChainMethod(buf, self, "MaxTimes",
		"n int", "n",
		"MaxTimes limits the number of calls to n times.")
	writeChainMethod(buf, self, "Times",
		"n int", "n",
		"Times declares the exact number of times this call is expected.")
	writeChainMethod(buf, self, "After",
		"preReq *Call", "preReq",
		"After declares that this call may only match after preReq is exhausted.")
}

func writeChainMethod(
	buf *bytes.Buffer,
	self string,
	method, params, args, doc string,
) {
	fmt.Fprintf(buf,
		"\n// %s — see *Call.%s.\n"+
			"func (c %s) %s(%s) %s {\n"+
			"\tc.Call = c.Call.%s(%s)\n"+
			"\treturn c\n}\n",
		doc, method, self, method, params, self, method, args,
	)
}

func writeInvoke(buf *bytes.Buffer, m int) {
	var typeParams, retVars, retAssign []string
	for i := 1; i <= m; i++ {
		typeParams = append(typeParams, fmt.Sprintf("R%d", i))
		retVars = append(retVars, fmt.Sprintf("r%d", i))
		retAssign = append(retAssign, fmt.Sprintf("\tr%d, _ := ret[%d].(R%d)", i, i-1, i))
	}
	retTuple := strings.Join(typeParams, ", ")

	fmt.Fprintf(buf,
		"\n// Invoke%d unpacks %d typed return value(s) from a []any call result.\n"+
			"func Invoke%d[%s any](ret []any) (%s) {\n"+
			"%s\n"+
			"\treturn %s\n}\n",
		m, m,
		m, retTuple, retTuple,
		strings.Join(retAssign, "\n"),
		strings.Join(retVars, ", "),
	)
}
