// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_source/definition (interfaces: S)
//
// Generated by this command:
//
//	mockgen -destination ../source_mock.go github.com/canonical/gomock/mockgen/internal/tests/import_source/definition S
//

// Package mock_source is a generated GoMock package.
package mock_source

import (
	gomock "github.com/canonical/gomock/gomock"
	source "github.com/canonical/gomock/mockgen/internal/tests/import_source/definition"
)

// MockS is a mock of S interface.
type MockS struct {
	ctrl     *gomock.Controller
	recorder *MockSMockRecorder
	isgomock struct{}
}

// MockSMockRecorder is the mock recorder for MockS.
type MockSMockRecorder struct {
	mock     *MockS
	fExpects []*gomock.Call1_0[source.X]
}

// NewMockS creates a new mock instance.
func NewMockS(ctrl *gomock.Controller) *MockS {
	mock := &MockS{ctrl: ctrl}
	mock.recorder = &MockSMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS) EXPECT() *MockSMockRecorder {
	return m.recorder
}

// F mocks base method.
func (m *MockS) F(arg0 source.X) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.fExpects, m.ctrl, m, "F", arg0)
}

// F indicates an expected call of F.
func (mr *MockSMockRecorder) F(arg0 any) *MockSFCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[source.X](mr.mock.ctrl.T, mr.mock, "F", gomock.EnsureMatcher(arg0))
	mr.fExpects = append(mr.fExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSFCall is the typed call wrapper for F.
type MockSFCall = gomock.Call1_0[source.X]
