// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_aliased (interfaces: S)
//
// Generated by this command:
//
//	mockgen -package import_aliased -destination source_mock.go github.com/canonical/gomock/mockgen/internal/tests/import_aliased S
//

// Package import_aliased is a generated GoMock package.
package import_aliased

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
)

// MockS is a mock of S interface.
type MockS struct {
	ctrl     *gomock.Controller
	recorder *MockSMockRecorder
	isgomock struct{}
}

// MockSMockRecorder is the mock recorder for MockS.
type MockSMockRecorder struct {
	mock     *MockS
	mExpects []*gomock.Call1_0[context.Context]
}

// NewMockS creates a new mock instance.
func NewMockS(ctrl *gomock.Controller) *MockS {
	mock := &MockS{ctrl: ctrl}
	mock.recorder = &MockSMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS) EXPECT() *MockSMockRecorder {
	return m.recorder
}

// M mocks base method.
func (m *MockS) M(ctx context.Context) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.mExpects, m.ctrl, m, "M", ctx)
}

// M indicates an expected call of M.
func (mr *MockSMockRecorder) M(ctx any) *MockSMCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[context.Context](mr.mock.ctrl.T, mr.mock, "M", gomock.EnsureMatcher(ctx))
	mr.mExpects = append(mr.mExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSMCall is the typed call wrapper for M.
type MockSMCall = gomock.Call1_0[context.Context]
