// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/build_flags (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=mock1/interfaces_mock.go -build_flags=-tags=tag1 . Interface
//

// Package mock_build_flags is a generated GoMock package.
package mock_build_flags

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// HelloWorld mocks base method.
func (m *MockInterface) HelloWorld() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "HelloWorld"))
}

// HelloWorld indicates an expected call of HelloWorld.
func (mr *MockInterfaceMockRecorder) HelloWorld() *MockInterfaceHelloWorldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HelloWorld", reflect.TypeOf((*MockInterface)(nil).HelloWorld))
	return &MockInterfaceHelloWorldCall{Call: call}
}

// MockInterfaceHelloWorldCall is the typed call wrapper for HelloWorld.
type MockInterfaceHelloWorldCall = gomock.Call0_1[string]
