// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/vendor_dep (interfaces: VendorsDep)
//
// Generated by this command:
//
//	mockgen -destination source_mock_package/mock.go github.com/canonical/gomock/mockgen/internal/tests/vendor_dep VendorsDep
//

// Package mock_vendor_dep is a generated GoMock package.
package mock_vendor_dep

import (
	gomock "github.com/canonical/gomock/gomock"
	present "golang.org/x/tools/present"
)

// MockVendorsDep is a mock of VendorsDep interface.
type MockVendorsDep struct {
	ctrl     *gomock.Controller
	recorder *MockVendorsDepMockRecorder
	isgomock struct{}
}

// MockVendorsDepMockRecorder is the mock recorder for MockVendorsDep.
type MockVendorsDepMockRecorder struct {
	mock       *MockVendorsDep
	fooExpects []*gomock.Call0_1[present.Elem]
}

// NewMockVendorsDep creates a new mock instance.
func NewMockVendorsDep(ctrl *gomock.Controller) *MockVendorsDep {
	mock := &MockVendorsDep{ctrl: ctrl}
	mock.recorder = &MockVendorsDepMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendorsDep) EXPECT() *MockVendorsDepMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockVendorsDep) Foo() present.Elem {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.fooExpects, m.ctrl, m, "Foo")
}

// Foo indicates an expected call of Foo.
func (mr *MockVendorsDepMockRecorder) Foo() *MockVendorsDepFooCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[present.Elem](mr.mock.ctrl.T, mr.mock, "Foo")
	mr.fooExpects = append(mr.fooExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockVendorsDepFooCall is the typed call wrapper for Foo.
type MockVendorsDepFooCall = gomock.Call0_1[present.Elem]
