// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/exclude (interfaces: GenerateMockForMe)
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=exclude -exclude_interfaces=IgnoreMe,IgnoreMe2 github.com/canonical/gomock/mockgen/internal/tests/exclude GenerateMockForMe
//

// Package exclude is a generated GoMock package.
package exclude

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockGenerateMockForMe is a mock of GenerateMockForMe interface.
type MockGenerateMockForMe struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateMockForMeMockRecorder
	isgomock struct{}
}

// MockGenerateMockForMeMockRecorder is the mock recorder for MockGenerateMockForMe.
type MockGenerateMockForMeMockRecorder struct {
	mock     *MockGenerateMockForMe
	bExpects []*gomock.Call0_1[int]
}

// NewMockGenerateMockForMe creates a new mock instance.
func NewMockGenerateMockForMe(ctrl *gomock.Controller) *MockGenerateMockForMe {
	mock := &MockGenerateMockForMe{ctrl: ctrl}
	mock.recorder = &MockGenerateMockForMeMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerateMockForMe) EXPECT() *MockGenerateMockForMeMockRecorder {
	return m.recorder
}

// B mocks base method.
func (m *MockGenerateMockForMe) B() int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.bExpects, m.ctrl, m, "B")
}

// B indicates an expected call of B.
func (mr *MockGenerateMockForMeMockRecorder) B() *MockGenerateMockForMeBCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[int](mr.mock.ctrl.T, mr.mock, "B")
	mr.bExpects = append(mr.bExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockGenerateMockForMeBCall is the typed call wrapper for B.
type MockGenerateMockForMeBCall = gomock.Call0_1[int]
