// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_collision/p2 (interfaces: Mything)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=internalpackage . Mything
//

// Package internalpackage is a generated GoMock package.
package internalpackage

import (
	gomock "github.com/canonical/gomock/gomock"
	internalpackage "github.com/canonical/gomock/mockgen/internal/tests/import_collision/internalpackage"
)

// MockMything is a mock of Mything interface.
type MockMything struct {
	ctrl     *gomock.Controller
	recorder *MockMythingMockRecorder
	isgomock struct{}
}

// MockMythingMockRecorder is the mock recorder for MockMything.
type MockMythingMockRecorder struct {
	mock          *MockMything
	doThatExpects []*gomock.Call1_1[int, internalpackage.FooExported]
}

// NewMockMything creates a new mock instance.
func NewMockMything(ctrl *gomock.Controller) *MockMything {
	mock := &MockMything{ctrl: ctrl}
	mock.recorder = &MockMythingMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMything) EXPECT() *MockMythingMockRecorder {
	return m.recorder
}

// DoThat mocks base method.
func (m *MockMything) DoThat(arg0 int) internalpackage.FooExported {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.doThatExpects, m.ctrl, m, "DoThat", arg0)
}

// DoThat indicates an expected call of DoThat.
func (mr *MockMythingMockRecorder) DoThat(arg0 any) *MockMythingDoThatCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[int, internalpackage.FooExported](mr.mock.ctrl.T, mr.mock, "DoThat", gomock.EnsureMatcher(arg0))
	mr.doThatExpects = append(mr.doThatExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMythingDoThatCall is the typed call wrapper for DoThat.
type MockMythingDoThatCall = gomock.Call1_1[int, internalpackage.FooExported]
