// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/sample (interfaces: Index,Embed,Embedded)
//
// Generated by this command:
//
//	mockgen -destination mock_user_test.go -package user_test go.uber.org/mock/sample Index,Embed,Embedded
//

// Package user_test is a generated GoMock package.
package user_test

import (
	bufio "bufio"
	bytes "bytes"
	hash "hash"
	template "html/template"
	io "io"
	http "net/http"
	reflect "reflect"
	template0 "text/template"

	gomock "go.uber.org/mock/gomock"
	imp1 "go.uber.org/mock/sample/imp1"
	imp2 "go.uber.org/mock/sample/imp2"
	imp3 "go.uber.org/mock/sample/imp3"
	imp_four "go.uber.org/mock/sample/imp4"
)

// MockIndex is a mock of Index interface.
type MockIndex struct {
	ctrl     *gomock.Controller
	recorder *MockIndexMockRecorder
	isgomock struct{}
}

// MockIndexMockRecorder is the mock recorder for MockIndex.
type MockIndexMockRecorder struct {
	mock *MockIndex
}

// NewMockIndex creates a new mock instance.
func NewMockIndex(ctrl *gomock.Controller) *MockIndex {
	mock := &MockIndex{ctrl: ctrl}
	mock.recorder = &MockIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndex) EXPECT() *MockIndexMockRecorder {
	return m.recorder
}

// Anon mocks base method.
func (m *MockIndex) Anon(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Anon", arg0)
}

// Anon indicates an expected call of Anon.
func (mr *MockIndexMockRecorder) Anon(arg0 any) *MockIndexAnonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Anon", reflect.TypeOf((*MockIndex)(nil).Anon), arg0)
	return &MockIndexAnonCall{Call: call}
}

// MockIndexAnonCall is the typed call wrapper for Anon.
type MockIndexAnonCall = gomock.Call1_0[string]

// Chan mocks base method.
func (m *MockIndex) Chan(a chan int, b chan<- hash.Hash) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Chan", a, b)
}

// Chan indicates an expected call of Chan.
func (mr *MockIndexMockRecorder) Chan(a, b any) *MockIndexChanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chan", reflect.TypeOf((*MockIndex)(nil).Chan), a, b)
	return &MockIndexChanCall{Call: call}
}

// MockIndexChanCall is the typed call wrapper for Chan.
type MockIndexChanCall = gomock.Call2_0[chan int, chan<- hash.Hash]

// ConcreteRet mocks base method.
func (m *MockIndex) ConcreteRet() chan<- bool {
	m.ctrl.T.Helper()
	return gomock.Invoke1[chan<- bool](m.ctrl.Call(m, "ConcreteRet"))
}

// ConcreteRet indicates an expected call of ConcreteRet.
func (mr *MockIndexMockRecorder) ConcreteRet() *MockIndexConcreteRetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcreteRet", reflect.TypeOf((*MockIndex)(nil).ConcreteRet))
	return &MockIndexConcreteRetCall{Call: call}
}

// MockIndexConcreteRetCall is the typed call wrapper for ConcreteRet.
type MockIndexConcreteRetCall = gomock.Call0_1[chan<- bool]

// Ellip mocks base method.
func (m *MockIndex) Ellip(fmt string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{fmt}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Ellip", varargs...)
}

// Ellip indicates an expected call of Ellip.
func (mr *MockIndexMockRecorder) Ellip(fmt any, args ...any) *MockIndexEllipCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fmt}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ellip", reflect.TypeOf((*MockIndex)(nil).Ellip), varargs...)
	return &MockIndexEllipCall{Call: call}
}

// MockIndexEllipCall wrap *gomock.Call
type MockIndexEllipCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexEllipCall) Return() *MockIndexEllipCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexEllipCall) Do(f func(string, ...any)) *MockIndexEllipCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexEllipCall) DoAndReturn(f func(string, ...any)) *MockIndexEllipCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EllipOnly mocks base method.
func (m *MockIndex) EllipOnly(arg0 ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "EllipOnly", varargs...)
}

// EllipOnly indicates an expected call of EllipOnly.
func (mr *MockIndexMockRecorder) EllipOnly(arg0 ...any) *MockIndexEllipOnlyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EllipOnly", reflect.TypeOf((*MockIndex)(nil).EllipOnly), arg0...)
	return &MockIndexEllipOnlyCall{Call: call}
}

// MockIndexEllipOnlyCall wrap *gomock.Call
type MockIndexEllipOnlyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIndexEllipOnlyCall) Return() *MockIndexEllipOnlyCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIndexEllipOnlyCall) Do(f func(...string)) *MockIndexEllipOnlyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIndexEllipOnlyCall) DoAndReturn(f func(...string)) *MockIndexEllipOnlyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ForeignFour mocks base method.
func (m *MockIndex) ForeignFour(arg0 imp_four.Imp4) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForeignFour", arg0)
}

// ForeignFour indicates an expected call of ForeignFour.
func (mr *MockIndexMockRecorder) ForeignFour(arg0 any) *MockIndexForeignFourCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForeignFour", reflect.TypeOf((*MockIndex)(nil).ForeignFour), arg0)
	return &MockIndexForeignFourCall{Call: call}
}

// MockIndexForeignFourCall is the typed call wrapper for ForeignFour.
type MockIndexForeignFourCall = gomock.Call1_0[imp_four.Imp4]

// ForeignOne mocks base method.
func (m *MockIndex) ForeignOne(arg0 imp1.Imp1) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForeignOne", arg0)
}

// ForeignOne indicates an expected call of ForeignOne.
func (mr *MockIndexMockRecorder) ForeignOne(arg0 any) *MockIndexForeignOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForeignOne", reflect.TypeOf((*MockIndex)(nil).ForeignOne), arg0)
	return &MockIndexForeignOneCall{Call: call}
}

// MockIndexForeignOneCall is the typed call wrapper for ForeignOne.
type MockIndexForeignOneCall = gomock.Call1_0[imp1.Imp1]

// ForeignThree mocks base method.
func (m *MockIndex) ForeignThree(arg0 imp3.Imp3) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForeignThree", arg0)
}

// ForeignThree indicates an expected call of ForeignThree.
func (mr *MockIndexMockRecorder) ForeignThree(arg0 any) *MockIndexForeignThreeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForeignThree", reflect.TypeOf((*MockIndex)(nil).ForeignThree), arg0)
	return &MockIndexForeignThreeCall{Call: call}
}

// MockIndexForeignThreeCall is the typed call wrapper for ForeignThree.
type MockIndexForeignThreeCall = gomock.Call1_0[imp3.Imp3]

// ForeignTwo mocks base method.
func (m *MockIndex) ForeignTwo(arg0 imp2.Imp2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForeignTwo", arg0)
}

// ForeignTwo indicates an expected call of ForeignTwo.
func (mr *MockIndexMockRecorder) ForeignTwo(arg0 any) *MockIndexForeignTwoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForeignTwo", reflect.TypeOf((*MockIndex)(nil).ForeignTwo), arg0)
	return &MockIndexForeignTwoCall{Call: call}
}

// MockIndexForeignTwoCall is the typed call wrapper for ForeignTwo.
type MockIndexForeignTwoCall = gomock.Call1_0[imp2.Imp2]

// Func mocks base method.
func (m *MockIndex) Func(f func(http.Request) (int, bool)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Func", f)
}

// Func indicates an expected call of Func.
func (mr *MockIndexMockRecorder) Func(f any) *MockIndexFuncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Func", reflect.TypeOf((*MockIndex)(nil).Func), f)
	return &MockIndexFuncCall{Call: call}
}

// MockIndexFuncCall is the typed call wrapper for Func.
type MockIndexFuncCall = gomock.Call1_0[func(http.Request) (int, bool)]

// Get mocks base method.
func (m *MockIndex) Get(key string) any {
	m.ctrl.T.Helper()
	return gomock.Invoke1[any](m.ctrl.Call(m, "Get", key))
}

// Get indicates an expected call of Get.
func (mr *MockIndexMockRecorder) Get(key any) *MockIndexGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIndex)(nil).Get), key)
	return &MockIndexGetCall{Call: call}
}

// MockIndexGetCall is the typed call wrapper for Get.
type MockIndexGetCall = gomock.Call1_1[string, any]

// GetTwo mocks base method.
func (m *MockIndex) GetTwo(key1, key2 string) (any, any) {
	m.ctrl.T.Helper()
	return gomock.Invoke2[any, any](m.ctrl.Call(m, "GetTwo", key1, key2))
}

// GetTwo indicates an expected call of GetTwo.
func (mr *MockIndexMockRecorder) GetTwo(key1, key2 any) *MockIndexGetTwoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwo", reflect.TypeOf((*MockIndex)(nil).GetTwo), key1, key2)
	return &MockIndexGetTwoCall{Call: call}
}

// MockIndexGetTwoCall is the typed call wrapper for GetTwo.
type MockIndexGetTwoCall = gomock.Call2_2[string, string, any, any]

// Map mocks base method.
func (m *MockIndex) Map(a map[int]hash.Hash) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Map", a)
}

// Map indicates an expected call of Map.
func (mr *MockIndexMockRecorder) Map(a any) *MockIndexMapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockIndex)(nil).Map), a)
	return &MockIndexMapCall{Call: call}
}

// MockIndexMapCall is the typed call wrapper for Map.
type MockIndexMapCall = gomock.Call1_0[map[int]hash.Hash]

// NillableRet mocks base method.
func (m *MockIndex) NillableRet() error {
	m.ctrl.T.Helper()
	return gomock.Invoke1[error](m.ctrl.Call(m, "NillableRet"))
}

// NillableRet indicates an expected call of NillableRet.
func (mr *MockIndexMockRecorder) NillableRet() *MockIndexNillableRetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NillableRet", reflect.TypeOf((*MockIndex)(nil).NillableRet))
	return &MockIndexNillableRetCall{Call: call}
}

// MockIndexNillableRetCall is the typed call wrapper for NillableRet.
type MockIndexNillableRetCall = gomock.Call0_1[error]

// Other mocks base method.
func (m *MockIndex) Other() hash.Hash {
	m.ctrl.T.Helper()
	return gomock.Invoke1[hash.Hash](m.ctrl.Call(m, "Other"))
}

// Other indicates an expected call of Other.
func (mr *MockIndexMockRecorder) Other() *MockIndexOtherCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Other", reflect.TypeOf((*MockIndex)(nil).Other))
	return &MockIndexOtherCall{Call: call}
}

// MockIndexOtherCall is the typed call wrapper for Other.
type MockIndexOtherCall = gomock.Call0_1[hash.Hash]

// Ptr mocks base method.
func (m *MockIndex) Ptr(arg *int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ptr", arg)
}

// Ptr indicates an expected call of Ptr.
func (mr *MockIndexMockRecorder) Ptr(arg any) *MockIndexPtrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ptr", reflect.TypeOf((*MockIndex)(nil).Ptr), arg)
	return &MockIndexPtrCall{Call: call}
}

// MockIndexPtrCall is the typed call wrapper for Ptr.
type MockIndexPtrCall = gomock.Call1_0[*int]

// Put mocks base method.
func (m *MockIndex) Put(key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", key, value)
}

// Put indicates an expected call of Put.
func (mr *MockIndexMockRecorder) Put(key, value any) *MockIndexPutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockIndex)(nil).Put), key, value)
	return &MockIndexPutCall{Call: call}
}

// MockIndexPutCall is the typed call wrapper for Put.
type MockIndexPutCall = gomock.Call2_0[string, any]

// Slice mocks base method.
func (m *MockIndex) Slice(a []int, b []byte) [3]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[3]int](m.ctrl.Call(m, "Slice", a, b))
}

// Slice indicates an expected call of Slice.
func (mr *MockIndexMockRecorder) Slice(a, b any) *MockIndexSliceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Slice", reflect.TypeOf((*MockIndex)(nil).Slice), a, b)
	return &MockIndexSliceCall{Call: call}
}

// MockIndexSliceCall is the typed call wrapper for Slice.
type MockIndexSliceCall = gomock.Call2_1[[]int, []byte, [3]int]

// Struct mocks base method.
func (m *MockIndex) Struct(a struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Struct", a)
}

// Struct indicates an expected call of Struct.
func (mr *MockIndexMockRecorder) Struct(a any) *MockIndexStructCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Struct", reflect.TypeOf((*MockIndex)(nil).Struct), a)
	return &MockIndexStructCall{Call: call}
}

// MockIndexStructCall is the typed call wrapper for Struct.
type MockIndexStructCall = gomock.Call1_0[struct{}]

// StructChan mocks base method.
func (m *MockIndex) StructChan(a chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StructChan", a)
}

// StructChan indicates an expected call of StructChan.
func (mr *MockIndexMockRecorder) StructChan(a any) *MockIndexStructChanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructChan", reflect.TypeOf((*MockIndex)(nil).StructChan), a)
	return &MockIndexStructChanCall{Call: call}
}

// MockIndexStructChanCall is the typed call wrapper for StructChan.
type MockIndexStructChanCall = gomock.Call1_0[chan struct{}]

// Summary mocks base method.
func (m *MockIndex) Summary(buf *bytes.Buffer, w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Summary", buf, w)
}

// Summary indicates an expected call of Summary.
func (mr *MockIndexMockRecorder) Summary(buf, w any) *MockIndexSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockIndex)(nil).Summary), buf, w)
	return &MockIndexSummaryCall{Call: call}
}

// MockIndexSummaryCall is the typed call wrapper for Summary.
type MockIndexSummaryCall = gomock.Call2_0[*bytes.Buffer, io.Writer]

// Templates mocks base method.
func (m *MockIndex) Templates(a template.CSS, b template0.FuncMap) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Templates", a, b)
}

// Templates indicates an expected call of Templates.
func (mr *MockIndexMockRecorder) Templates(a, b any) *MockIndexTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Templates", reflect.TypeOf((*MockIndex)(nil).Templates), a, b)
	return &MockIndexTemplatesCall{Call: call}
}

// MockIndexTemplatesCall is the typed call wrapper for Templates.
type MockIndexTemplatesCall = gomock.Call2_0[template.CSS, template0.FuncMap]

// MockEmbed is a mock of Embed interface.
type MockEmbed struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedMockRecorder
	isgomock struct{}
}

// MockEmbedMockRecorder is the mock recorder for MockEmbed.
type MockEmbedMockRecorder struct {
	mock *MockEmbed
}

// NewMockEmbed creates a new mock instance.
func NewMockEmbed(ctrl *gomock.Controller) *MockEmbed {
	mock := &MockEmbed{ctrl: ctrl}
	mock.recorder = &MockEmbedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbed) EXPECT() *MockEmbedMockRecorder {
	return m.recorder
}

// EmbeddedMethod mocks base method.
func (m *MockEmbed) EmbeddedMethod() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmbeddedMethod")
}

// EmbeddedMethod indicates an expected call of EmbeddedMethod.
func (mr *MockEmbedMockRecorder) EmbeddedMethod() *MockEmbedEmbeddedMethodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbeddedMethod", reflect.TypeOf((*MockEmbed)(nil).EmbeddedMethod))
	return &MockEmbedEmbeddedMethodCall{Call: call}
}

// MockEmbedEmbeddedMethodCall is the typed call wrapper for EmbeddedMethod.
type MockEmbedEmbeddedMethodCall = gomock.Call0_0

// ForeignEmbeddedMethod mocks base method.
func (m *MockEmbed) ForeignEmbeddedMethod() *bufio.Reader {
	m.ctrl.T.Helper()
	return gomock.Invoke1[*bufio.Reader](m.ctrl.Call(m, "ForeignEmbeddedMethod"))
}

// ForeignEmbeddedMethod indicates an expected call of ForeignEmbeddedMethod.
func (mr *MockEmbedMockRecorder) ForeignEmbeddedMethod() *MockEmbedForeignEmbeddedMethodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForeignEmbeddedMethod", reflect.TypeOf((*MockEmbed)(nil).ForeignEmbeddedMethod))
	return &MockEmbedForeignEmbeddedMethodCall{Call: call}
}

// MockEmbedForeignEmbeddedMethodCall is the typed call wrapper for ForeignEmbeddedMethod.
type MockEmbedForeignEmbeddedMethodCall = gomock.Call0_1[*bufio.Reader]

// ImplicitPackage mocks base method.
func (m *MockEmbed) ImplicitPackage(s string, t imp1.ImpT, st []imp1.ImpT, pt *imp1.ImpT, ct chan imp1.ImpT) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ImplicitPackage", s, t, st, pt, ct)
}

// ImplicitPackage indicates an expected call of ImplicitPackage.
func (mr *MockEmbedMockRecorder) ImplicitPackage(s, t, st, pt, ct any) *MockEmbedImplicitPackageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImplicitPackage", reflect.TypeOf((*MockEmbed)(nil).ImplicitPackage), s, t, st, pt, ct)
	return &MockEmbedImplicitPackageCall{Call: call}
}

// MockEmbedImplicitPackageCall is the typed call wrapper for ImplicitPackage.
type MockEmbedImplicitPackageCall = gomock.Call5_0[string, imp1.ImpT, []imp1.ImpT, *imp1.ImpT, chan imp1.ImpT]

// RegularMethod mocks base method.
func (m *MockEmbed) RegularMethod() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegularMethod")
}

// RegularMethod indicates an expected call of RegularMethod.
func (mr *MockEmbedMockRecorder) RegularMethod() *MockEmbedRegularMethodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegularMethod", reflect.TypeOf((*MockEmbed)(nil).RegularMethod))
	return &MockEmbedRegularMethodCall{Call: call}
}

// MockEmbedRegularMethodCall is the typed call wrapper for RegularMethod.
type MockEmbedRegularMethodCall = gomock.Call0_0

// MockEmbedded is a mock of Embedded interface.
type MockEmbedded struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddedMockRecorder
	isgomock struct{}
}

// MockEmbeddedMockRecorder is the mock recorder for MockEmbedded.
type MockEmbeddedMockRecorder struct {
	mock *MockEmbedded
}

// NewMockEmbedded creates a new mock instance.
func NewMockEmbedded(ctrl *gomock.Controller) *MockEmbedded {
	mock := &MockEmbedded{ctrl: ctrl}
	mock.recorder = &MockEmbeddedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedded) EXPECT() *MockEmbeddedMockRecorder {
	return m.recorder
}

// EmbeddedMethod mocks base method.
func (m *MockEmbedded) EmbeddedMethod() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmbeddedMethod")
}

// EmbeddedMethod indicates an expected call of EmbeddedMethod.
func (mr *MockEmbeddedMockRecorder) EmbeddedMethod() *MockEmbeddedEmbeddedMethodCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbeddedMethod", reflect.TypeOf((*MockEmbedded)(nil).EmbeddedMethod))
	return &MockEmbeddedEmbeddedMethodCall{Call: call}
}

// MockEmbeddedEmbeddedMethodCall is the typed call wrapper for EmbeddedMethod.
type MockEmbeddedEmbeddedMethodCall = gomock.Call0_0
