// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/mock_in_test_package (interfaces: Finder)
//
// Generated by this command:
//
//	mockgen --destination=mock_test.go --package=users_test go.uber.org/mock/mockgen/internal/tests/mock_in_test_package Finder
//

// Package users_test is a generated GoMock package.
package users_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	users "go.uber.org/mock/mockgen/internal/tests/mock_in_test_package"
)

// MockFinder is a mock of Finder interface.
type MockFinder struct {
	ctrl     *gomock.Controller
	recorder *MockFinderMockRecorder
	isgomock struct{}
}

// MockFinderMockRecorder is the mock recorder for MockFinder.
type MockFinderMockRecorder struct {
	mock *MockFinder
}

// NewMockFinder creates a new mock instance.
func NewMockFinder(ctrl *gomock.Controller) *MockFinder {
	mock := &MockFinder{ctrl: ctrl}
	mock.recorder = &MockFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinder) EXPECT() *MockFinderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFinder) Add(u users.User) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", u)
}

// Add indicates an expected call of Add.
func (mr *MockFinderMockRecorder) Add(u any) *MockFinderAddCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFinder)(nil).Add), u)
	return &MockFinderAddCall{Call: call}
}

// MockFinderAddCall is the typed call wrapper for Add.
type MockFinderAddCall = gomock.Call1_0[users.User]

// FindUser mocks base method.
func (m *MockFinder) FindUser(name string) users.User {
	m.ctrl.T.Helper()
	return gomock.Invoke1[users.User](m.ctrl.Call(m, "FindUser", name))
}

// FindUser indicates an expected call of FindUser.
func (mr *MockFinderMockRecorder) FindUser(name any) *MockFinderFindUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockFinder)(nil).FindUser), name)
	return &MockFinderFindUserCall{Call: call}
}

// MockFinderFindUserCall is the typed call wrapper for FindUser.
type MockFinderFindUserCall = gomock.Call1_1[string, users.User]
