// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/mock_in_test_package (interfaces: Finder)
//
// Generated by this command:
//
//	mockgen --destination=mock_test.go --package=users_test github.com/canonical/gomock/mockgen/internal/tests/mock_in_test_package Finder
//

// Package users_test is a generated GoMock package.
package users_test

import (
	gomock "github.com/canonical/gomock/gomock"
	users "github.com/canonical/gomock/mockgen/internal/tests/mock_in_test_package"
)

// MockFinder is a mock of Finder interface.
type MockFinder struct {
	ctrl     *gomock.Controller
	recorder *MockFinderMockRecorder
	isgomock struct{}
}

// MockFinderMockRecorder is the mock recorder for MockFinder.
type MockFinderMockRecorder struct {
	mock            *MockFinder
	addExpects      []*gomock.Call1_0[users.User]
	findUserExpects []*gomock.Call1_1[string, users.User]
}

// NewMockFinder creates a new mock instance.
func NewMockFinder(ctrl *gomock.Controller) *MockFinder {
	mock := &MockFinder{ctrl: ctrl}
	mock.recorder = &MockFinderMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinder) EXPECT() *MockFinderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFinder) Add(u users.User) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.addExpects, m.ctrl, m, "Add", u)
}

// Add indicates an expected call of Add.
func (mr *MockFinderMockRecorder) Add(u any) *MockFinderAddCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[users.User](mr.mock.ctrl.T, mr.mock, "Add", gomock.EnsureMatcher(u))
	mr.addExpects = append(mr.addExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFinderAddCall is the typed call wrapper for Add.
type MockFinderAddCall = gomock.Call1_0[users.User]

// FindUser mocks base method.
func (m *MockFinder) FindUser(name string) users.User {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.findUserExpects, m.ctrl, m, "FindUser", name)
}

// FindUser indicates an expected call of FindUser.
func (mr *MockFinderMockRecorder) FindUser(name any) *MockFinderFindUserCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[string, users.User](mr.mock.ctrl.T, mr.mock, "FindUser", gomock.EnsureMatcher(name))
	mr.findUserExpects = append(mr.findUserExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFinderFindUserCall is the typed call wrapper for FindUser.
type MockFinderFindUserCall = gomock.Call1_1[string, users.User]
