// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/sanitization (interfaces: AnyMock)
//
// Generated by this command:
//
//	mockgen -destination mockout/mock.go -package mockout . AnyMock
//

// Package mockout is a generated GoMock package.
package mockout

import (
	gomock "github.com/canonical/gomock/gomock"
	any0 "github.com/canonical/gomock/mockgen/internal/tests/sanitization/any"
)

// MockAnyMock is a mock of AnyMock interface.
type MockAnyMock struct {
	ctrl     *gomock.Controller
	recorder *MockAnyMockMockRecorder
	isgomock struct{}
}

// MockAnyMockMockRecorder is the mock recorder for MockAnyMock.
type MockAnyMockMockRecorder struct {
	mock      *MockAnyMock
	doExpects []*gomock.Call2_0[*any0.Any, int]
}

// NewMockAnyMock creates a new mock instance.
func NewMockAnyMock(ctrl *gomock.Controller) *MockAnyMock {
	mock := &MockAnyMock{ctrl: ctrl}
	mock.recorder = &MockAnyMockMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnyMock) EXPECT() *MockAnyMockMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockAnyMock) Do(a *any0.Any, b int) {
	m.ctrl.T.Helper()
	gomock.Dispatch2_0(&m.recorder.doExpects, m.ctrl, m, "Do", a, b)
}

// Do indicates an expected call of Do.
func (mr *MockAnyMockMockRecorder) Do(a, b any) *MockAnyMockDoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_0[*any0.Any, int](mr.mock.ctrl.T, mr.mock, "Do", gomock.EnsureMatcher(a), gomock.EnsureMatcher(b))
	mr.doExpects = append(mr.doExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAnyMockDoCall is the typed call wrapper for Do.
type MockAnyMockDoCall = gomock.Call2_0[*any0.Any, int]
