// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/self_package (interfaces: Methods)
//
// Generated by this command:
//
//	mockgen -package core -self_package github.com/canonical/gomock/mockgen/internal/tests/self_package -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/self_package Methods
//

// Package core is a generated GoMock package.
package core

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockMethods is a mock of Methods interface.
type MockMethods struct {
	ctrl     *gomock.Controller
	recorder *MockMethodsMockRecorder
	isgomock struct{}
}

// MockMethodsMockRecorder is the mock recorder for MockMethods.
type MockMethodsMockRecorder struct {
	mock           *MockMethods
	getInfoExpects []*gomock.Call0_1[Info]
}

// NewMockMethods creates a new mock instance.
func NewMockMethods(ctrl *gomock.Controller) *MockMethods {
	mock := &MockMethods{ctrl: ctrl}
	mock.recorder = &MockMethodsMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMethods) EXPECT() *MockMethodsMockRecorder {
	return m.recorder
}

// getInfo mocks base method.
func (m *MockMethods) getInfo() Info {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.getInfoExpects, m.ctrl, m, "getInfo")
}

// getInfo indicates an expected call of getInfo.
func (mr *MockMethodsMockRecorder) getInfo() *MockMethodsgetInfoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[Info](mr.mock.ctrl.T, mr.mock, "getInfo")
	mr.getInfoExpects = append(mr.getInfoExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMethodsgetInfoCall is the typed call wrapper for getInfo.
type MockMethodsgetInfoCall = gomock.Call0_1[Info]
