// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/unexported_method (interfaces: Example)
//
// Generated by this command:
//
//	mockgen -package bugreport -destination internal/tests/unexported_method/mock_bugreport.go github.com/canonical/gomock/mockgen/internal/tests/unexported_method Example
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockExample is a mock of Example interface.
type MockExample struct {
	ctrl     *gomock.Controller
	recorder *MockExampleMockRecorder
	isgomock struct{}
}

// MockExampleMockRecorder is the mock recorder for MockExample.
type MockExampleMockRecorder struct {
	mock              *MockExample
	someMethodExpects []*gomock.Call1_1[string, string]
}

// NewMockExample creates a new mock instance.
func NewMockExample(ctrl *gomock.Controller) *MockExample {
	mock := &MockExample{ctrl: ctrl}
	mock.recorder = &MockExampleMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExample) EXPECT() *MockExampleMockRecorder {
	return m.recorder
}

// someMethod mocks base method.
func (m *MockExample) someMethod(arg0 string) string {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.someMethodExpects, m.ctrl, m, "someMethod", arg0)
}

// someMethod indicates an expected call of someMethod.
func (mr *MockExampleMockRecorder) someMethod(arg0 any) *MockExamplesomeMethodCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[string, string](mr.mock.ctrl.T, mr.mock, "someMethod", gomock.EnsureMatcher(arg0))
	mr.someMethodExpects = append(mr.someMethodExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExamplesomeMethodCall is the typed call wrapper for someMethod.
type MockExamplesomeMethodCall = gomock.Call1_1[string, string]
