// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/generics (interfaces: Universe)
//
// Generated by this command:
//
//	mockgen --destination=source/mock_generics.go --package=source . Universe
//

// Package source is a generated GoMock package.
package source

import (
	gomock "github.com/canonical/gomock/gomock"
	constraints "golang.org/x/exp/constraints"
)

// MockUniverse is a mock of Universe interface.
type MockUniverse[T constraints.Signed] struct {
	ctrl     *gomock.Controller
	recorder *MockUniverseMockRecorder[T]
	isgomock struct{}
}

// MockUniverseMockRecorder is the mock recorder for MockUniverse.
type MockUniverseMockRecorder[T constraints.Signed] struct {
	mock         *MockUniverse[T]
	waterExpects []*gomock.Call1_1[T, []T]
}

// NewMockUniverse creates a new mock instance.
func NewMockUniverse[T constraints.Signed](ctrl *gomock.Controller) *MockUniverse[T] {
	mock := &MockUniverse[T]{ctrl: ctrl}
	mock.recorder = &MockUniverseMockRecorder[T]{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniverse[T]) EXPECT() *MockUniverseMockRecorder[T] {
	return m.recorder
}

// Water mocks base method.
func (m *MockUniverse[T]) Water(arg0 T) []T {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.waterExpects, m.ctrl, m, "Water", arg0)
}

// Water indicates an expected call of Water.
func (mr *MockUniverseMockRecorder[T]) Water(arg0 any) *MockUniverseWaterCall[T] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, []T](mr.mock.ctrl.T, mr.mock, "Water", gomock.EnsureMatcher(arg0))
	mr.waterExpects = append(mr.waterExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockUniverseWaterCall is the typed call wrapper for Water.
type MockUniverseWaterCall[T constraints.Signed] = gomock.Call1_1[T, []T]
