// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/gomock_test (interfaces: Foo)

// Package gomock_test is a generated GoMock package.
package gomock_test

import (
	reflect "reflect"

	"github.com/canonical/gomock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
	isgomock struct{}
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockFoo) Bar(arg0 string) string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "Bar", arg0))
}

// Bar indicates an expected call of Bar.
func (mr *MockFooMockRecorder) Bar(arg0 any) *MockFooBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "Bar", reflect.TypeOf((*MockFoo)(nil).Bar), arg0,
	)
	return &MockFooBarCall{Call: call}
}

// MockFooBarCall is the typed call wrapper for Bar.
type MockFooBarCall = gomock.Call1_1[string, string]

// String mocks base method.
func (m *MockFoo) String() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "String"))
}

// String indicates an expected call of String.
func (mr *MockFooMockRecorder) String() *MockFooStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "String", reflect.TypeOf((*MockFoo)(nil).String),
	)
	return &MockFooStringCall{Call: call}
}

// MockFooStringCall is the typed call wrapper for String.
type MockFooStringCall = gomock.Call0_1[string]
