// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface Source
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
	ersatz "github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface/ersatz"
	ersatz0 "github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface/other/ersatz"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockSource) Bar() Baz {
	m.ctrl.T.Helper()
	return gomock.Invoke1[Baz](m.ctrl.Call(m, "Bar"))
}

// Bar indicates an expected call of Bar.
func (mr *MockSourceMockRecorder) Bar() *MockSourceBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockSource)(nil).Bar))
	return &MockSourceBarCall{Call: call}
}

// MockSourceBarCall is the typed call wrapper for Bar.
type MockSourceBarCall = gomock.Call0_1[Baz]

// Error mocks base method.
func (m *MockSource) Error() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "Error"))
}

// Error indicates an expected call of Error.
func (mr *MockSourceMockRecorder) Error() *MockSourceErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSource)(nil).Error))
	return &MockSourceErrorCall{Call: call}
}

// MockSourceErrorCall is the typed call wrapper for Error.
type MockSourceErrorCall = gomock.Call0_1[string]

// Ersatz mocks base method.
func (m *MockSource) Ersatz() ersatz.Return {
	m.ctrl.T.Helper()
	return gomock.Invoke1[ersatz.Return](m.ctrl.Call(m, "Ersatz"))
}

// Ersatz indicates an expected call of Ersatz.
func (mr *MockSourceMockRecorder) Ersatz() *MockSourceErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ersatz", reflect.TypeOf((*MockSource)(nil).Ersatz))
	return &MockSourceErsatzCall{Call: call}
}

// MockSourceErsatzCall is the typed call wrapper for Ersatz.
type MockSourceErsatzCall = gomock.Call0_1[ersatz.Return]

// OtherErsatz mocks base method.
func (m *MockSource) OtherErsatz() ersatz0.Return {
	m.ctrl.T.Helper()
	return gomock.Invoke1[ersatz0.Return](m.ctrl.Call(m, "OtherErsatz"))
}

// OtherErsatz indicates an expected call of OtherErsatz.
func (mr *MockSourceMockRecorder) OtherErsatz() *MockSourceOtherErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OtherErsatz", reflect.TypeOf((*MockSource)(nil).OtherErsatz))
	return &MockSourceOtherErsatzCall{Call: call}
}

// MockSourceOtherErsatzCall is the typed call wrapper for OtherErsatz.
type MockSourceOtherErsatzCall = gomock.Call0_1[ersatz0.Return]
