// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface Source
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	gomock "github.com/canonical/gomock/gomock"
	ersatz "github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface/ersatz"
	ersatz0 "github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface/other/ersatz"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock               *MockSource
	barExpects         []*gomock.Call0_1[Baz]
	errorExpects       []*gomock.Call0_1[string]
	ersatzExpects      []*gomock.Call0_1[ersatz.Return]
	otherErsatzExpects []*gomock.Call0_1[ersatz0.Return]
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockSource) Bar() Baz {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.barExpects, m.ctrl, m, "Bar")
}

// Bar indicates an expected call of Bar.
func (mr *MockSourceMockRecorder) Bar() *MockSourceBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[Baz](mr.mock.ctrl.T, mr.mock, "Bar")
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceBarCall is the typed call wrapper for Bar.
type MockSourceBarCall = gomock.Call0_1[Baz]

// Error mocks base method.
func (m *MockSource) Error() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.errorExpects, m.ctrl, m, "Error")
}

// Error indicates an expected call of Error.
func (mr *MockSourceMockRecorder) Error() *MockSourceErrorCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Error")
	mr.errorExpects = append(mr.errorExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceErrorCall is the typed call wrapper for Error.
type MockSourceErrorCall = gomock.Call0_1[string]

// Ersatz mocks base method.
func (m *MockSource) Ersatz() ersatz.Return {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.ersatzExpects, m.ctrl, m, "Ersatz")
}

// Ersatz indicates an expected call of Ersatz.
func (mr *MockSourceMockRecorder) Ersatz() *MockSourceErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[ersatz.Return](mr.mock.ctrl.T, mr.mock, "Ersatz")
	mr.ersatzExpects = append(mr.ersatzExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceErsatzCall is the typed call wrapper for Ersatz.
type MockSourceErsatzCall = gomock.Call0_1[ersatz.Return]

// OtherErsatz mocks base method.
func (m *MockSource) OtherErsatz() ersatz0.Return {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.otherErsatzExpects, m.ctrl, m, "OtherErsatz")
}

// OtherErsatz indicates an expected call of OtherErsatz.
func (mr *MockSourceMockRecorder) OtherErsatz() *MockSourceOtherErsatzCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[ersatz0.Return](mr.mock.ctrl.T, mr.mock, "OtherErsatz")
	mr.otherErsatzExpects = append(mr.otherErsatzExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceOtherErsatzCall is the typed call wrapper for OtherErsatz.
type MockSourceOtherErsatzCall = gomock.Call0_1[ersatz0.Return]
