// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface (interfaces: Net)
//
// Generated by this command:
//
//	mockgen -destination net_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface Net
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/canonical/gomock/gomock"
)

// MockNet is a mock of Net interface.
type MockNet struct {
	ctrl     *gomock.Controller
	recorder *MockNetMockRecorder
	isgomock struct{}
}

// MockNetMockRecorder is the mock recorder for MockNet.
type MockNetMockRecorder struct {
	mock *MockNet
}

// NewMockNet creates a new mock instance.
func NewMockNet(ctrl *gomock.Controller) *MockNet {
	mock := &MockNet{ctrl: ctrl}
	mock.recorder = &MockNetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNet) EXPECT() *MockNetMockRecorder {
	return m.recorder
}

// Header mocks base method.
func (m *MockNet) Header() http.Header {
	m.ctrl.T.Helper()
	return gomock.Invoke1[http.Header](m.ctrl.Call(m, "Header"))
}

// Header indicates an expected call of Header.
func (mr *MockNetMockRecorder) Header() *MockNetHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockNet)(nil).Header))
	return &MockNetHeaderCall{Call: call}
}

// MockNetHeaderCall is the typed call wrapper for Header.
type MockNetHeaderCall = gomock.Call0_1[http.Header]

// Write mocks base method.
func (m *MockNet) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Invoke2[int, error](m.ctrl.Call(m, "Write", arg0))
}

// Write indicates an expected call of Write.
func (mr *MockNetMockRecorder) Write(arg0 any) *MockNetWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockNet)(nil).Write), arg0)
	return &MockNetWriteCall{Call: call}
}

// MockNetWriteCall is the typed call wrapper for Write.
type MockNetWriteCall = gomock.Call1_2[[]byte, int, error]

// WriteHeader mocks base method.
func (m *MockNet) WriteHeader(statusCode int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteHeader", statusCode)
}

// WriteHeader indicates an expected call of WriteHeader.
func (mr *MockNetMockRecorder) WriteHeader(statusCode any) *MockNetWriteHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHeader", reflect.TypeOf((*MockNet)(nil).WriteHeader), statusCode)
	return &MockNetWriteHeaderCall{Call: call}
}

// MockNetWriteHeaderCall is the typed call wrapper for WriteHeader.
type MockNetWriteHeaderCall = gomock.Call1_0[int]
