// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface (interfaces: Net)
//
// Generated by this command:
//
//	mockgen -destination net_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/import_embedded_interface Net
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	http "net/http"

	gomock "github.com/canonical/gomock/gomock"
)

// MockNet is a mock of Net interface.
type MockNet struct {
	ctrl     *gomock.Controller
	recorder *MockNetMockRecorder
	isgomock struct{}
}

// MockNetMockRecorder is the mock recorder for MockNet.
type MockNetMockRecorder struct {
	mock               *MockNet
	headerExpects      []*gomock.Call0_1[http.Header]
	writeExpects       []*gomock.Call1_2[[]byte, int, error]
	writeHeaderExpects []*gomock.Call1_0[int]
}

// NewMockNet creates a new mock instance.
func NewMockNet(ctrl *gomock.Controller) *MockNet {
	mock := &MockNet{ctrl: ctrl}
	mock.recorder = &MockNetMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNet) EXPECT() *MockNetMockRecorder {
	return m.recorder
}

// Header mocks base method.
func (m *MockNet) Header() http.Header {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.headerExpects, m.ctrl, m, "Header")
}

// Header indicates an expected call of Header.
func (mr *MockNetMockRecorder) Header() *MockNetHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[http.Header](mr.mock.ctrl.T, mr.mock, "Header")
	mr.headerExpects = append(mr.headerExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockNetHeaderCall is the typed call wrapper for Header.
type MockNetHeaderCall = gomock.Call0_1[http.Header]

// Write mocks base method.
func (m *MockNet) Write(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.writeExpects, m.ctrl, m, "Write", arg0)
}

// Write indicates an expected call of Write.
func (mr *MockNetMockRecorder) Write(arg0 any) *MockNetWriteCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[[]byte, int, error](mr.mock.ctrl.T, mr.mock, "Write", gomock.EnsureMatcher(arg0))
	mr.writeExpects = append(mr.writeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockNetWriteCall is the typed call wrapper for Write.
type MockNetWriteCall = gomock.Call1_2[[]byte, int, error]

// WriteHeader mocks base method.
func (m *MockNet) WriteHeader(statusCode int) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.writeHeaderExpects, m.ctrl, m, "WriteHeader", statusCode)
}

// WriteHeader indicates an expected call of WriteHeader.
func (mr *MockNetMockRecorder) WriteHeader(statusCode any) *MockNetWriteHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[int](mr.mock.ctrl.T, mr.mock, "WriteHeader", gomock.EnsureMatcher(statusCode))
	mr.writeHeaderExpects = append(mr.writeHeaderExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockNetWriteHeaderCall is the typed call wrapper for WriteHeader.
type MockNetWriteHeaderCall = gomock.Call1_0[int]
