// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/build_flags (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=mock2/interfaces_mock.go -build_flags=-race -tags=tag2 . Interface
//

// Package mock_build_flags is a generated GoMock package.
package mock_build_flags

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock       *MockInterface
	fooExpects []*gomock.Call0_0
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockInterface) Foo() {
	m.ctrl.T.Helper()
	gomock.Dispatch0_0(&m.recorder.fooExpects, m.ctrl, m, "Foo")
}

// Foo indicates an expected call of Foo.
func (mr *MockInterfaceMockRecorder) Foo() *MockInterfaceFooCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_0(mr.mock.ctrl.T, mr.mock, "Foo")
	mr.fooExpects = append(mr.fooExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockInterfaceFooCall is the typed call wrapper for Foo.
type MockInterfaceFooCall = gomock.Call0_0
