// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/gomock (interfaces: Matcher)
//
// Generated by this command:
//
//	mockgen -destination internal/mock_gomock/mock_matcher.go github.com/canonical/gomock/gomock Matcher
//

// Package mock_gomock is a generated GoMock package.
package mock_gomock

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Matches mocks base method.
func (m *MockMatcher) Matches(x any) bool {
	m.ctrl.T.Helper()
	return gomock.Invoke1[bool](m.ctrl.Call(m, "Matches", x))
}

// Matches indicates an expected call of Matches.
func (mr *MockMatcherMockRecorder) Matches(x any) *MockMatcherMatchesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallTyped(
		mr.mock, "Matches", 1, 1, false,
		func() []any {
			var r1 bool
			return []any{r1}
		}, x)
	return &MockMatcherMatchesCall{Call: call}
}

// MockMatcherMatchesCall is the typed call wrapper for Matches.
type MockMatcherMatchesCall = gomock.Call1_1[any, bool]

// String mocks base method.
func (m *MockMatcher) String() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "String"))
}

// String indicates an expected call of String.
func (mr *MockMatcherMockRecorder) String() *MockMatcherStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallTyped(
		mr.mock, "String", 0, 1, false,
		func() []any {
			var r1 string
			return []any{r1}
		})
	return &MockMatcherStringCall{Call: call}
}

// MockMatcherStringCall is the typed call wrapper for String.
type MockMatcherStringCall = gomock.Call0_1[string]
