// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/custom_package_name/greeter (interfaces: InputMaker)
//
// Generated by this command:
//
//	mockgen -destination greeter_mock_test.go -package greeter go.uber.org/mock/mockgen/internal/tests/custom_package_name/greeter InputMaker
//

// Package greeter is a generated GoMock package.
package greeter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "go.uber.org/mock/mockgen/internal/tests/custom_package_name/client/v1"
)

// MockInputMaker is a mock of InputMaker interface.
type MockInputMaker struct {
	ctrl     *gomock.Controller
	recorder *MockInputMakerMockRecorder
	isgomock struct{}
}

// MockInputMakerMockRecorder is the mock recorder for MockInputMaker.
type MockInputMakerMockRecorder struct {
	mock *MockInputMaker
}

// NewMockInputMaker creates a new mock instance.
func NewMockInputMaker(ctrl *gomock.Controller) *MockInputMaker {
	mock := &MockInputMaker{ctrl: ctrl}
	mock.recorder = &MockInputMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputMaker) EXPECT() *MockInputMakerMockRecorder {
	return m.recorder
}

// MakeInput mocks base method.
func (m *MockInputMaker) MakeInput() client.GreetInput {
	m.ctrl.T.Helper()
	return gomock.Invoke1[client.GreetInput](m.ctrl.Call(m, "MakeInput"))
}

// MakeInput indicates an expected call of MakeInput.
func (mr *MockInputMakerMockRecorder) MakeInput() *MockInputMakerMakeInputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeInput", reflect.TypeOf((*MockInputMaker)(nil).MakeInput))
	return &MockInputMakerMakeInputCall{Call: call}
}

// MockInputMakerMakeInputCall is the typed call wrapper for MakeInput.
type MockInputMakerMakeInputCall = gomock.Call0_1[client.GreetInput]
