// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/custom_package_name/greeter (interfaces: InputMaker)
//
// Generated by this command:
//
//	mockgen -destination greeter_mock_test.go -package greeter github.com/canonical/gomock/mockgen/internal/tests/custom_package_name/greeter InputMaker
//

// Package greeter is a generated GoMock package.
package greeter

import (
	gomock "github.com/canonical/gomock/gomock"
	client "github.com/canonical/gomock/mockgen/internal/tests/custom_package_name/client/v1"
)

// MockInputMaker is a mock of InputMaker interface.
type MockInputMaker struct {
	ctrl     *gomock.Controller
	recorder *MockInputMakerMockRecorder
	isgomock struct{}
}

// MockInputMakerMockRecorder is the mock recorder for MockInputMaker.
type MockInputMakerMockRecorder struct {
	mock             *MockInputMaker
	makeInputExpects []*gomock.Call0_1[client.GreetInput]
}

// NewMockInputMaker creates a new mock instance.
func NewMockInputMaker(ctrl *gomock.Controller) *MockInputMaker {
	mock := &MockInputMaker{ctrl: ctrl}
	mock.recorder = &MockInputMakerMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputMaker) EXPECT() *MockInputMakerMockRecorder {
	return m.recorder
}

// MakeInput mocks base method.
func (m *MockInputMaker) MakeInput() client.GreetInput {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.makeInputExpects, m.ctrl, m, "MakeInput")
}

// MakeInput indicates an expected call of MakeInput.
func (mr *MockInputMakerMockRecorder) MakeInput() *MockInputMakerMakeInputCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[client.GreetInput](mr.mock.ctrl.T, mr.mock, "MakeInput")
	mr.makeInputExpects = append(mr.makeInputExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockInputMakerMakeInputCall is the typed call wrapper for MakeInput.
type MockInputMakerMakeInputCall = gomock.Call0_1[client.GreetInput]
