// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/generated_identifier_conflict (interfaces: Example)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package bugreport github.com/canonical/gomock/mockgen/internal/tests/generated_identifier_conflict Example
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockExample is a mock of Example interface.
type MockExample struct {
	ctrl     *gomock.Controller
	recorder *MockExampleMockRecorder
	isgomock struct{}
}

// MockExampleMockRecorder is the mock recorder for MockExample.
type MockExampleMockRecorder struct {
	mock                *MockExample
	methodExpects       []*gomock.Call4_0[int, int, int, int]
	varargMethodExpects []*gomock.Call4V_0[int, int, int, int, int]
}

// NewMockExample creates a new mock instance.
func NewMockExample(ctrl *gomock.Controller) *MockExample {
	mock := &MockExample{ctrl: ctrl}
	mock.recorder = &MockExampleMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExample) EXPECT() *MockExampleMockRecorder {
	return m.recorder
}

// Method mocks base method.
func (m_2 *MockExample) Method(_m, _mr, m, mr int) {
	m_2.ctrl.T.Helper()
	gomock.Dispatch4_0(&m_2.recorder.methodExpects, m_2.ctrl, m_2, "Method", _m, _mr, m, mr)
}

// Method indicates an expected call of Method.
func (mr_2 *MockExampleMockRecorder) Method(_m, _mr, m, mr any) *MockExampleMethodCall {
	mr_2.mock.ctrl.T.Helper()
	call := gomock.NewCall4_0[int, int, int, int](mr_2.mock.ctrl.T, mr_2.mock, "Method", gomock.EnsureMatcher(_m), gomock.EnsureMatcher(_mr), gomock.EnsureMatcher(m), gomock.EnsureMatcher(mr))
	mr_2.methodExpects = append(mr_2.methodExpects, call)
	mr_2.mock.ctrl.Track(call.Call)
	return call
}

// MockExampleMethodCall is the typed call wrapper for Method.
type MockExampleMethodCall = gomock.Call4_0[int, int, int, int]

// VarargMethod mocks base method.
func (m *MockExample) VarargMethod(_s, _x, a, ret int, varargs ...int) {
	m.ctrl.T.Helper()
	gomock.Dispatch4V_0(&m.recorder.varargMethodExpects, m.ctrl, m, "VarargMethod", _s, _x, a, ret, varargs...)
}

// VarargMethod indicates an expected call of VarargMethod.
func (mr *MockExampleMockRecorder) VarargMethod(_s, _x, a, ret any, varargs ...any) *MockExampleVarargMethodCall {
	mr.mock.ctrl.T.Helper()
	varArgs := gomock.EnsureVariadicMatcher(varargs)
	call := gomock.NewCall4V_0[int, int, int, int, int](mr.mock.ctrl.T, mr.mock, "VarargMethod", gomock.EnsureMatcher(_s), gomock.EnsureMatcher(_x), gomock.EnsureMatcher(a), gomock.EnsureMatcher(ret), varArgs)
	mr.varargMethodExpects = append(mr.varargMethodExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExampleVarargMethodCall is the typed call wrapper for VarargMethod.
type MockExampleVarargMethodCall = gomock.Call4V_0[int, int, int, int, int]
