// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/generated_identifier_conflict (interfaces: Example)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package bugreport go.uber.org/mock/mockgen/internal/tests/generated_identifier_conflict Example
//

// Package bugreport is a generated GoMock package.
package bugreport

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExample is a mock of Example interface.
type MockExample struct {
	ctrl     *gomock.Controller
	recorder *MockExampleMockRecorder
	isgomock struct{}
}

// MockExampleMockRecorder is the mock recorder for MockExample.
type MockExampleMockRecorder struct {
	mock *MockExample
}

// NewMockExample creates a new mock instance.
func NewMockExample(ctrl *gomock.Controller) *MockExample {
	mock := &MockExample{ctrl: ctrl}
	mock.recorder = &MockExampleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExample) EXPECT() *MockExampleMockRecorder {
	return m.recorder
}

// Method mocks base method.
func (m_2 *MockExample) Method(_m, _mr, m, mr int) {
	m_2.ctrl.T.Helper()
	m_2.ctrl.Call(m_2, "Method", _m, _mr, m, mr)
}

// Method indicates an expected call of Method.
func (mr_2 *MockExampleMockRecorder) Method(_m, _mr, m, mr any) *MockExampleMethodCall {
	mr_2.mock.ctrl.T.Helper()
	call := mr_2.mock.ctrl.RecordCallWithMethodType(mr_2.mock, "Method", reflect.TypeOf((*MockExample)(nil).Method), _m, _mr, m, mr)
	return &MockExampleMethodCall{Call: call}
}

// MockExampleMethodCall is the typed call wrapper for Method.
type MockExampleMethodCall = gomock.Call4_0[int, int, int, int]

// VarargMethod mocks base method.
func (m *MockExample) VarargMethod(_s, _x, a, ret int, varargs ...int) {
	m.ctrl.T.Helper()
	varargs_2 := []any{_s, _x, a, ret}
	for _, a_2 := range varargs {
		varargs_2 = append(varargs_2, a_2)
	}
	m.ctrl.Call(m, "VarargMethod", varargs_2...)
}

// VarargMethod indicates an expected call of VarargMethod.
func (mr *MockExampleMockRecorder) VarargMethod(_s, _x, a, ret any, varargs ...any) *MockExampleVarargMethodCall {
	mr.mock.ctrl.T.Helper()
	varargs_2 := append([]any{_s, _x, a, ret}, varargs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VarargMethod", reflect.TypeOf((*MockExample)(nil).VarargMethod), varargs_2...)
	return &MockExampleVarargMethodCall{Call: call}
}

// MockExampleVarargMethodCall wrap *gomock.Call
type MockExampleVarargMethodCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockExampleVarargMethodCall) Return() *MockExampleVarargMethodCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockExampleVarargMethodCall) Do(f func(int, int, int, int, ...int)) *MockExampleVarargMethodCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockExampleVarargMethodCall) DoAndReturn(f func(int, int, int, int, ...int)) *MockExampleVarargMethodCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
