// Code generated by MockGen. DO NOT EDIT.
// Source: golang.org/x/tools/present (interfaces: Elem)
//
// Generated by this command:
//
//	mockgen -destination mock.go -package vendor_pkg golang.org/x/tools/present Elem
//

// Package vendor_pkg is a generated GoMock package.
package vendor_pkg

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockElem is a mock of Elem interface.
type MockElem struct {
	ctrl     *gomock.Controller
	recorder *MockElemMockRecorder
	isgomock struct{}
}

// MockElemMockRecorder is the mock recorder for MockElem.
type MockElemMockRecorder struct {
	mock                *MockElem
	templateNameExpects []*gomock.Call0_1[string]
}

// NewMockElem creates a new mock instance.
func NewMockElem(ctrl *gomock.Controller) *MockElem {
	mock := &MockElem{ctrl: ctrl}
	mock.recorder = &MockElemMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElem) EXPECT() *MockElemMockRecorder {
	return m.recorder
}

// TemplateName mocks base method.
func (m *MockElem) TemplateName() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.templateNameExpects, m.ctrl, m, "TemplateName")
}

// TemplateName indicates an expected call of TemplateName.
func (mr *MockElemMockRecorder) TemplateName() *MockElemTemplateNameCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "TemplateName")
	mr.templateNameExpects = append(mr.templateNameExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockElemTemplateNameCall is the typed call wrapper for TemplateName.
type MockElemTemplateNameCall = gomock.Call0_1[string]
