// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/const_array_length (interfaces: I)
//
// Generated by this command:
//
//	mockgen -package const_length -destination mock.go github.com/canonical/gomock/mockgen/internal/tests/const_array_length I
//

// Package const_length is a generated GoMock package.
package const_length

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
	isgomock struct{}
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock         *MockI
	barExpects   []*gomock.Call0_1[[2]int]
	bazExpects   []*gomock.Call0_1[[127]int]
	corgeExpects []*gomock.Call0_1[[7]int]
	fooExpects   []*gomock.Call0_1[[2]int]
	quuxExpects  []*gomock.Call0_1[[3]int]
	quxExpects   []*gomock.Call0_1[[3]int]
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockI) Bar() [2]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.barExpects, m.ctrl, m, "Bar")
}

// Bar indicates an expected call of Bar.
func (mr *MockIMockRecorder) Bar() *MockIBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[2]int](mr.mock.ctrl.T, mr.mock, "Bar")
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockIBarCall is the typed call wrapper for Bar.
type MockIBarCall = gomock.Call0_1[[2]int]

// Baz mocks base method.
func (m *MockI) Baz() [127]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.bazExpects, m.ctrl, m, "Baz")
}

// Baz indicates an expected call of Baz.
func (mr *MockIMockRecorder) Baz() *MockIBazCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[127]int](mr.mock.ctrl.T, mr.mock, "Baz")
	mr.bazExpects = append(mr.bazExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockIBazCall is the typed call wrapper for Baz.
type MockIBazCall = gomock.Call0_1[[127]int]

// Corge mocks base method.
func (m *MockI) Corge() [7]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.corgeExpects, m.ctrl, m, "Corge")
}

// Corge indicates an expected call of Corge.
func (mr *MockIMockRecorder) Corge() *MockICorgeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[7]int](mr.mock.ctrl.T, mr.mock, "Corge")
	mr.corgeExpects = append(mr.corgeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockICorgeCall is the typed call wrapper for Corge.
type MockICorgeCall = gomock.Call0_1[[7]int]

// Foo mocks base method.
func (m *MockI) Foo() [2]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.fooExpects, m.ctrl, m, "Foo")
}

// Foo indicates an expected call of Foo.
func (mr *MockIMockRecorder) Foo() *MockIFooCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[2]int](mr.mock.ctrl.T, mr.mock, "Foo")
	mr.fooExpects = append(mr.fooExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockIFooCall is the typed call wrapper for Foo.
type MockIFooCall = gomock.Call0_1[[2]int]

// Quux mocks base method.
func (m *MockI) Quux() [3]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.quuxExpects, m.ctrl, m, "Quux")
}

// Quux indicates an expected call of Quux.
func (mr *MockIMockRecorder) Quux() *MockIQuuxCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[3]int](mr.mock.ctrl.T, mr.mock, "Quux")
	mr.quuxExpects = append(mr.quuxExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockIQuuxCall is the typed call wrapper for Quux.
type MockIQuuxCall = gomock.Call0_1[[3]int]

// Qux mocks base method.
func (m *MockI) Qux() [3]int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.quxExpects, m.ctrl, m, "Qux")
}

// Qux indicates an expected call of Qux.
func (mr *MockIMockRecorder) Qux() *MockIQuxCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[[3]int](mr.mock.ctrl.T, mr.mock, "Qux")
	mr.quxExpects = append(mr.quxExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockIQuxCall is the typed call wrapper for Qux.
type MockIQuxCall = gomock.Call0_1[[3]int]
