// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/const_array_length (interfaces: I)
//
// Generated by this command:
//
//	mockgen -package const_length -destination mock.go go.uber.org/mock/mockgen/internal/tests/const_array_length I
//

// Package const_length is a generated GoMock package.
package const_length

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
	isgomock struct{}
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockI) Bar() [2]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[2]int](m.ctrl.Call(m, "Bar"))
}

// Bar indicates an expected call of Bar.
func (mr *MockIMockRecorder) Bar() *MockIBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockI)(nil).Bar))
	return &MockIBarCall{Call: call}
}

// MockIBarCall is the typed call wrapper for Bar.
type MockIBarCall = gomock.Call0_1[[2]int]

// Baz mocks base method.
func (m *MockI) Baz() [127]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[127]int](m.ctrl.Call(m, "Baz"))
}

// Baz indicates an expected call of Baz.
func (mr *MockIMockRecorder) Baz() *MockIBazCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Baz", reflect.TypeOf((*MockI)(nil).Baz))
	return &MockIBazCall{Call: call}
}

// MockIBazCall is the typed call wrapper for Baz.
type MockIBazCall = gomock.Call0_1[[127]int]

// Corge mocks base method.
func (m *MockI) Corge() [7]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[7]int](m.ctrl.Call(m, "Corge"))
}

// Corge indicates an expected call of Corge.
func (mr *MockIMockRecorder) Corge() *MockICorgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Corge", reflect.TypeOf((*MockI)(nil).Corge))
	return &MockICorgeCall{Call: call}
}

// MockICorgeCall is the typed call wrapper for Corge.
type MockICorgeCall = gomock.Call0_1[[7]int]

// Foo mocks base method.
func (m *MockI) Foo() [2]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[2]int](m.ctrl.Call(m, "Foo"))
}

// Foo indicates an expected call of Foo.
func (mr *MockIMockRecorder) Foo() *MockIFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockI)(nil).Foo))
	return &MockIFooCall{Call: call}
}

// MockIFooCall is the typed call wrapper for Foo.
type MockIFooCall = gomock.Call0_1[[2]int]

// Quux mocks base method.
func (m *MockI) Quux() [3]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[3]int](m.ctrl.Call(m, "Quux"))
}

// Quux indicates an expected call of Quux.
func (mr *MockIMockRecorder) Quux() *MockIQuuxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quux", reflect.TypeOf((*MockI)(nil).Quux))
	return &MockIQuuxCall{Call: call}
}

// MockIQuuxCall is the typed call wrapper for Quux.
type MockIQuuxCall = gomock.Call0_1[[3]int]

// Qux mocks base method.
func (m *MockI) Qux() [3]int {
	m.ctrl.T.Helper()
	return gomock.Invoke1[[3]int](m.ctrl.Call(m, "Qux"))
}

// Qux indicates an expected call of Qux.
func (mr *MockIMockRecorder) Qux() *MockIQuxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Qux", reflect.TypeOf((*MockI)(nil).Qux))
	return &MockIQuxCall{Call: call}
}

// MockIQuxCall is the typed call wrapper for Qux.
type MockIQuxCall = gomock.Call0_1[[3]int]
