// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/typed (interfaces: Bar)
//
// Generated by this command:
//
//	mockgen --destination=source/mock_generics_test.go --package source github.com/canonical/gomock/mockgen/internal/tests/typed Bar
//

// Package source is a generated GoMock package.
package source

import (
	gomock "github.com/canonical/gomock/gomock"
	typed "github.com/canonical/gomock/mockgen/internal/tests/typed"
	other "github.com/canonical/gomock/mockgen/internal/tests/typed/other"
)

// MockBar is a mock of Bar interface.
type MockBar[T any, R any] struct {
	ctrl     *gomock.Controller
	recorder *MockBarMockRecorder[T, R]
	isgomock struct{}
}

// MockBarMockRecorder is the mock recorder for MockBar.
type MockBarMockRecorder[T any, R any] struct {
	mock             *MockBar[T, R]
	eightExpects     []*gomock.Call1_1[T, other.Two[T, R]]
	eighteenExpects  []*gomock.Call0_2[typed.Iface[*other.Five], error]
	elevenExpects    []*gomock.Call0_2[*other.One[T], error]
	fifteenExpects   []*gomock.Call0_2[typed.Iface[typed.StructType], error]
	fiveExpects      []*gomock.Call1_1[T, typed.Baz[T]]
	fourExpects      []*gomock.Call1_1[T, typed.Foo[T, R]]
	fourteenExpects  []*gomock.Call0_2[*typed.Foo[typed.StructType, typed.StructType2], error]
	nineExpects      []*gomock.Call1_0[typed.Iface[T]]
	nineteenExpects  []*gomock.Call0_1[typed.AliasType]
	oneExpects       []*gomock.Call1_1[string, string]
	sevenExpects     []*gomock.Call1_1[T, other.One[T]]
	seventeenExpects []*gomock.Call0_2[*typed.Foo[other.Three, other.Four], error]
	sixExpects       []*gomock.Call1_1[T, *typed.Baz[T]]
	sixteenExpects   []*gomock.Call0_2[typed.Baz[other.Three], error]
	tenExpects       []*gomock.Call1_0[*T]
	thirteenExpects  []*gomock.Call0_2[typed.Baz[typed.StructType], error]
	threeExpects     []*gomock.Call1_1[T, R]
	twelveExpects    []*gomock.Call0_2[*other.Two[T, R], error]
	twoExpects       []*gomock.Call1_1[T, string]
}

// NewMockBar creates a new mock instance.
func NewMockBar[T any, R any](ctrl *gomock.Controller) *MockBar[T, R] {
	mock := &MockBar[T, R]{ctrl: ctrl}
	mock.recorder = &MockBarMockRecorder[T, R]{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBar[T, R]) EXPECT() *MockBarMockRecorder[T, R] {
	return m.recorder
}

// Eight mocks base method.
func (m *MockBar[T, R]) Eight(arg0 T) other.Two[T, R] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.eightExpects, m.ctrl, m, "Eight", arg0)
}

// Eight indicates an expected call of Eight.
func (mr *MockBarMockRecorder[T, R]) Eight(arg0 any) *MockBarEightCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, other.Two[T, R]](mr.mock.ctrl.T, mr.mock, "Eight", gomock.EnsureMatcher(arg0))
	mr.eightExpects = append(mr.eightExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarEightCall is the typed call wrapper for Eight.
type MockBarEightCall[T any, R any] = gomock.Call1_1[T, other.Two[T, R]]

// Eighteen mocks base method.
func (m *MockBar[T, R]) Eighteen() (typed.Iface[*other.Five], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.eighteenExpects, m.ctrl, m, "Eighteen")
}

// Eighteen indicates an expected call of Eighteen.
func (mr *MockBarMockRecorder[T, R]) Eighteen() *MockBarEighteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[typed.Iface[*other.Five], error](mr.mock.ctrl.T, mr.mock, "Eighteen")
	mr.eighteenExpects = append(mr.eighteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarEighteenCall is the typed call wrapper for Eighteen.
type MockBarEighteenCall[T any, R any] = gomock.Call0_2[typed.Iface[*other.Five], error]

// Eleven mocks base method.
func (m *MockBar[T, R]) Eleven() (*other.One[T], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.elevenExpects, m.ctrl, m, "Eleven")
}

// Eleven indicates an expected call of Eleven.
func (mr *MockBarMockRecorder[T, R]) Eleven() *MockBarElevenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[*other.One[T], error](mr.mock.ctrl.T, mr.mock, "Eleven")
	mr.elevenExpects = append(mr.elevenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarElevenCall is the typed call wrapper for Eleven.
type MockBarElevenCall[T any, R any] = gomock.Call0_2[*other.One[T], error]

// Fifteen mocks base method.
func (m *MockBar[T, R]) Fifteen() (typed.Iface[typed.StructType], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.fifteenExpects, m.ctrl, m, "Fifteen")
}

// Fifteen indicates an expected call of Fifteen.
func (mr *MockBarMockRecorder[T, R]) Fifteen() *MockBarFifteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[typed.Iface[typed.StructType], error](mr.mock.ctrl.T, mr.mock, "Fifteen")
	mr.fifteenExpects = append(mr.fifteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarFifteenCall is the typed call wrapper for Fifteen.
type MockBarFifteenCall[T any, R any] = gomock.Call0_2[typed.Iface[typed.StructType], error]

// Five mocks base method.
func (m *MockBar[T, R]) Five(arg0 T) typed.Baz[T] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.fiveExpects, m.ctrl, m, "Five", arg0)
}

// Five indicates an expected call of Five.
func (mr *MockBarMockRecorder[T, R]) Five(arg0 any) *MockBarFiveCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, typed.Baz[T]](mr.mock.ctrl.T, mr.mock, "Five", gomock.EnsureMatcher(arg0))
	mr.fiveExpects = append(mr.fiveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarFiveCall is the typed call wrapper for Five.
type MockBarFiveCall[T any, R any] = gomock.Call1_1[T, typed.Baz[T]]

// Four mocks base method.
func (m *MockBar[T, R]) Four(arg0 T) typed.Foo[T, R] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.fourExpects, m.ctrl, m, "Four", arg0)
}

// Four indicates an expected call of Four.
func (mr *MockBarMockRecorder[T, R]) Four(arg0 any) *MockBarFourCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, typed.Foo[T, R]](mr.mock.ctrl.T, mr.mock, "Four", gomock.EnsureMatcher(arg0))
	mr.fourExpects = append(mr.fourExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarFourCall is the typed call wrapper for Four.
type MockBarFourCall[T any, R any] = gomock.Call1_1[T, typed.Foo[T, R]]

// Fourteen mocks base method.
func (m *MockBar[T, R]) Fourteen() (*typed.Foo[typed.StructType, typed.StructType2], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.fourteenExpects, m.ctrl, m, "Fourteen")
}

// Fourteen indicates an expected call of Fourteen.
func (mr *MockBarMockRecorder[T, R]) Fourteen() *MockBarFourteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[*typed.Foo[typed.StructType, typed.StructType2], error](mr.mock.ctrl.T, mr.mock, "Fourteen")
	mr.fourteenExpects = append(mr.fourteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarFourteenCall is the typed call wrapper for Fourteen.
type MockBarFourteenCall[T any, R any] = gomock.Call0_2[*typed.Foo[typed.StructType, typed.StructType2], error]

// Nine mocks base method.
func (m *MockBar[T, R]) Nine(arg0 typed.Iface[T]) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.nineExpects, m.ctrl, m, "Nine", arg0)
}

// Nine indicates an expected call of Nine.
func (mr *MockBarMockRecorder[T, R]) Nine(arg0 any) *MockBarNineCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[typed.Iface[T]](mr.mock.ctrl.T, mr.mock, "Nine", gomock.EnsureMatcher(arg0))
	mr.nineExpects = append(mr.nineExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarNineCall is the typed call wrapper for Nine.
type MockBarNineCall[T any, R any] = gomock.Call1_0[typed.Iface[T]]

// Nineteen mocks base method.
func (m *MockBar[T, R]) Nineteen() typed.AliasType {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.nineteenExpects, m.ctrl, m, "Nineteen")
}

// Nineteen indicates an expected call of Nineteen.
func (mr *MockBarMockRecorder[T, R]) Nineteen() *MockBarNineteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[typed.AliasType](mr.mock.ctrl.T, mr.mock, "Nineteen")
	mr.nineteenExpects = append(mr.nineteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarNineteenCall is the typed call wrapper for Nineteen.
type MockBarNineteenCall[T any, R any] = gomock.Call0_1[typed.AliasType]

// One mocks base method.
func (m *MockBar[T, R]) One(arg0 string) string {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.oneExpects, m.ctrl, m, "One", arg0)
}

// One indicates an expected call of One.
func (mr *MockBarMockRecorder[T, R]) One(arg0 any) *MockBarOneCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[string, string](mr.mock.ctrl.T, mr.mock, "One", gomock.EnsureMatcher(arg0))
	mr.oneExpects = append(mr.oneExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarOneCall is the typed call wrapper for One.
type MockBarOneCall[T any, R any] = gomock.Call1_1[string, string]

// Seven mocks base method.
func (m *MockBar[T, R]) Seven(arg0 T) other.One[T] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.sevenExpects, m.ctrl, m, "Seven", arg0)
}

// Seven indicates an expected call of Seven.
func (mr *MockBarMockRecorder[T, R]) Seven(arg0 any) *MockBarSevenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, other.One[T]](mr.mock.ctrl.T, mr.mock, "Seven", gomock.EnsureMatcher(arg0))
	mr.sevenExpects = append(mr.sevenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarSevenCall is the typed call wrapper for Seven.
type MockBarSevenCall[T any, R any] = gomock.Call1_1[T, other.One[T]]

// Seventeen mocks base method.
func (m *MockBar[T, R]) Seventeen() (*typed.Foo[other.Three, other.Four], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.seventeenExpects, m.ctrl, m, "Seventeen")
}

// Seventeen indicates an expected call of Seventeen.
func (mr *MockBarMockRecorder[T, R]) Seventeen() *MockBarSeventeenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[*typed.Foo[other.Three, other.Four], error](mr.mock.ctrl.T, mr.mock, "Seventeen")
	mr.seventeenExpects = append(mr.seventeenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarSeventeenCall is the typed call wrapper for Seventeen.
type MockBarSeventeenCall[T any, R any] = gomock.Call0_2[*typed.Foo[other.Three, other.Four], error]

// Six mocks base method.
func (m *MockBar[T, R]) Six(arg0 T) *typed.Baz[T] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.sixExpects, m.ctrl, m, "Six", arg0)
}

// Six indicates an expected call of Six.
func (mr *MockBarMockRecorder[T, R]) Six(arg0 any) *MockBarSixCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, *typed.Baz[T]](mr.mock.ctrl.T, mr.mock, "Six", gomock.EnsureMatcher(arg0))
	mr.sixExpects = append(mr.sixExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarSixCall is the typed call wrapper for Six.
type MockBarSixCall[T any, R any] = gomock.Call1_1[T, *typed.Baz[T]]

// Sixteen mocks base method.
func (m *MockBar[T, R]) Sixteen() (typed.Baz[other.Three], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.sixteenExpects, m.ctrl, m, "Sixteen")
}

// Sixteen indicates an expected call of Sixteen.
func (mr *MockBarMockRecorder[T, R]) Sixteen() *MockBarSixteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[typed.Baz[other.Three], error](mr.mock.ctrl.T, mr.mock, "Sixteen")
	mr.sixteenExpects = append(mr.sixteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarSixteenCall is the typed call wrapper for Sixteen.
type MockBarSixteenCall[T any, R any] = gomock.Call0_2[typed.Baz[other.Three], error]

// Ten mocks base method.
func (m *MockBar[T, R]) Ten(arg0 *T) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.tenExpects, m.ctrl, m, "Ten", arg0)
}

// Ten indicates an expected call of Ten.
func (mr *MockBarMockRecorder[T, R]) Ten(arg0 any) *MockBarTenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[*T](mr.mock.ctrl.T, mr.mock, "Ten", gomock.EnsureMatcher(arg0))
	mr.tenExpects = append(mr.tenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarTenCall is the typed call wrapper for Ten.
type MockBarTenCall[T any, R any] = gomock.Call1_0[*T]

// Thirteen mocks base method.
func (m *MockBar[T, R]) Thirteen() (typed.Baz[typed.StructType], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.thirteenExpects, m.ctrl, m, "Thirteen")
}

// Thirteen indicates an expected call of Thirteen.
func (mr *MockBarMockRecorder[T, R]) Thirteen() *MockBarThirteenCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[typed.Baz[typed.StructType], error](mr.mock.ctrl.T, mr.mock, "Thirteen")
	mr.thirteenExpects = append(mr.thirteenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarThirteenCall is the typed call wrapper for Thirteen.
type MockBarThirteenCall[T any, R any] = gomock.Call0_2[typed.Baz[typed.StructType], error]

// Three mocks base method.
func (m *MockBar[T, R]) Three(arg0 T) R {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.threeExpects, m.ctrl, m, "Three", arg0)
}

// Three indicates an expected call of Three.
func (mr *MockBarMockRecorder[T, R]) Three(arg0 any) *MockBarThreeCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, R](mr.mock.ctrl.T, mr.mock, "Three", gomock.EnsureMatcher(arg0))
	mr.threeExpects = append(mr.threeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarThreeCall is the typed call wrapper for Three.
type MockBarThreeCall[T any, R any] = gomock.Call1_1[T, R]

// Twelve mocks base method.
func (m *MockBar[T, R]) Twelve() (*other.Two[T, R], error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.twelveExpects, m.ctrl, m, "Twelve")
}

// Twelve indicates an expected call of Twelve.
func (mr *MockBarMockRecorder[T, R]) Twelve() *MockBarTwelveCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[*other.Two[T, R], error](mr.mock.ctrl.T, mr.mock, "Twelve")
	mr.twelveExpects = append(mr.twelveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarTwelveCall is the typed call wrapper for Twelve.
type MockBarTwelveCall[T any, R any] = gomock.Call0_2[*other.Two[T, R], error]

// Two mocks base method.
func (m *MockBar[T, R]) Two(arg0 T) string {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.twoExpects, m.ctrl, m, "Two", arg0)
}

// Two indicates an expected call of Two.
func (mr *MockBarMockRecorder[T, R]) Two(arg0 any) *MockBarTwoCall[T, R] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[T, string](mr.mock.ctrl.T, mr.mock, "Two", gomock.EnsureMatcher(arg0))
	mr.twoExpects = append(mr.twoExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarTwoCall is the typed call wrapper for Two.
type MockBarTwoCall[T any, R any] = gomock.Call1_1[T, string]
