// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/typed (interfaces: ExternalConstraint)
//
// Generated by this command:
//
//	mockgen --destination=source/mock_external_test.go --package source github.com/canonical/gomock/mockgen/internal/tests/typed ExternalConstraint
//

// Package source is a generated GoMock package.
package source

import (
	gomock "github.com/canonical/gomock/gomock"
	typed "github.com/canonical/gomock/mockgen/internal/tests/typed"
	other "github.com/canonical/gomock/mockgen/internal/tests/typed/other"
	constraints "golang.org/x/exp/constraints"
)

// MockExternalConstraint is a mock of ExternalConstraint interface.
type MockExternalConstraint[I constraints.Integer, F constraints.Float] struct {
	ctrl     *gomock.Controller
	recorder *MockExternalConstraintMockRecorder[I, F]
	isgomock struct{}
}

// MockExternalConstraintMockRecorder is the mock recorder for MockExternalConstraint.
type MockExternalConstraintMockRecorder[I constraints.Integer, F constraints.Float] struct {
	mock         *MockExternalConstraint[I, F]
	eightExpects []*gomock.Call1_1[F, other.Two[I, F]]
	fiveExpects  []*gomock.Call1_1[I, typed.Baz[F]]
	fourExpects  []*gomock.Call1_1[I, typed.Foo[I, F]]
	nineExpects  []*gomock.Call1_0[typed.Iface[I]]
	oneExpects   []*gomock.Call1_1[string, string]
	sevenExpects []*gomock.Call1_1[I, other.One[I]]
	sixExpects   []*gomock.Call1_1[I, *typed.Baz[F]]
	tenExpects   []*gomock.Call1_0[*I]
	threeExpects []*gomock.Call1_1[I, F]
	twoExpects   []*gomock.Call1_1[I, string]
}

// NewMockExternalConstraint creates a new mock instance.
func NewMockExternalConstraint[I constraints.Integer, F constraints.Float](ctrl *gomock.Controller) *MockExternalConstraint[I, F] {
	mock := &MockExternalConstraint[I, F]{ctrl: ctrl}
	mock.recorder = &MockExternalConstraintMockRecorder[I, F]{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalConstraint[I, F]) EXPECT() *MockExternalConstraintMockRecorder[I, F] {
	return m.recorder
}

// Eight mocks base method.
func (m *MockExternalConstraint[I, F]) Eight(arg0 F) other.Two[I, F] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.eightExpects, m.ctrl, m, "Eight", arg0)
}

// Eight indicates an expected call of Eight.
func (mr *MockExternalConstraintMockRecorder[I, F]) Eight(arg0 any) *MockExternalConstraintEightCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[F, other.Two[I, F]](mr.mock.ctrl.T, mr.mock, "Eight", gomock.EnsureMatcher(arg0))
	mr.eightExpects = append(mr.eightExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintEightCall is the typed call wrapper for Eight.
type MockExternalConstraintEightCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[F, other.Two[I, F]]

// Five mocks base method.
func (m *MockExternalConstraint[I, F]) Five(arg0 I) typed.Baz[F] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.fiveExpects, m.ctrl, m, "Five", arg0)
}

// Five indicates an expected call of Five.
func (mr *MockExternalConstraintMockRecorder[I, F]) Five(arg0 any) *MockExternalConstraintFiveCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, typed.Baz[F]](mr.mock.ctrl.T, mr.mock, "Five", gomock.EnsureMatcher(arg0))
	mr.fiveExpects = append(mr.fiveExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintFiveCall is the typed call wrapper for Five.
type MockExternalConstraintFiveCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, typed.Baz[F]]

// Four mocks base method.
func (m *MockExternalConstraint[I, F]) Four(arg0 I) typed.Foo[I, F] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.fourExpects, m.ctrl, m, "Four", arg0)
}

// Four indicates an expected call of Four.
func (mr *MockExternalConstraintMockRecorder[I, F]) Four(arg0 any) *MockExternalConstraintFourCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, typed.Foo[I, F]](mr.mock.ctrl.T, mr.mock, "Four", gomock.EnsureMatcher(arg0))
	mr.fourExpects = append(mr.fourExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintFourCall is the typed call wrapper for Four.
type MockExternalConstraintFourCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, typed.Foo[I, F]]

// Nine mocks base method.
func (m *MockExternalConstraint[I, F]) Nine(arg0 typed.Iface[I]) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.nineExpects, m.ctrl, m, "Nine", arg0)
}

// Nine indicates an expected call of Nine.
func (mr *MockExternalConstraintMockRecorder[I, F]) Nine(arg0 any) *MockExternalConstraintNineCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[typed.Iface[I]](mr.mock.ctrl.T, mr.mock, "Nine", gomock.EnsureMatcher(arg0))
	mr.nineExpects = append(mr.nineExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintNineCall is the typed call wrapper for Nine.
type MockExternalConstraintNineCall[I constraints.Integer, F constraints.Float] = gomock.Call1_0[typed.Iface[I]]

// One mocks base method.
func (m *MockExternalConstraint[I, F]) One(arg0 string) string {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.oneExpects, m.ctrl, m, "One", arg0)
}

// One indicates an expected call of One.
func (mr *MockExternalConstraintMockRecorder[I, F]) One(arg0 any) *MockExternalConstraintOneCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[string, string](mr.mock.ctrl.T, mr.mock, "One", gomock.EnsureMatcher(arg0))
	mr.oneExpects = append(mr.oneExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintOneCall is the typed call wrapper for One.
type MockExternalConstraintOneCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[string, string]

// Seven mocks base method.
func (m *MockExternalConstraint[I, F]) Seven(arg0 I) other.One[I] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.sevenExpects, m.ctrl, m, "Seven", arg0)
}

// Seven indicates an expected call of Seven.
func (mr *MockExternalConstraintMockRecorder[I, F]) Seven(arg0 any) *MockExternalConstraintSevenCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, other.One[I]](mr.mock.ctrl.T, mr.mock, "Seven", gomock.EnsureMatcher(arg0))
	mr.sevenExpects = append(mr.sevenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintSevenCall is the typed call wrapper for Seven.
type MockExternalConstraintSevenCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, other.One[I]]

// Six mocks base method.
func (m *MockExternalConstraint[I, F]) Six(arg0 I) *typed.Baz[F] {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.sixExpects, m.ctrl, m, "Six", arg0)
}

// Six indicates an expected call of Six.
func (mr *MockExternalConstraintMockRecorder[I, F]) Six(arg0 any) *MockExternalConstraintSixCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, *typed.Baz[F]](mr.mock.ctrl.T, mr.mock, "Six", gomock.EnsureMatcher(arg0))
	mr.sixExpects = append(mr.sixExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintSixCall is the typed call wrapper for Six.
type MockExternalConstraintSixCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, *typed.Baz[F]]

// Ten mocks base method.
func (m *MockExternalConstraint[I, F]) Ten(arg0 *I) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.tenExpects, m.ctrl, m, "Ten", arg0)
}

// Ten indicates an expected call of Ten.
func (mr *MockExternalConstraintMockRecorder[I, F]) Ten(arg0 any) *MockExternalConstraintTenCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[*I](mr.mock.ctrl.T, mr.mock, "Ten", gomock.EnsureMatcher(arg0))
	mr.tenExpects = append(mr.tenExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintTenCall is the typed call wrapper for Ten.
type MockExternalConstraintTenCall[I constraints.Integer, F constraints.Float] = gomock.Call1_0[*I]

// Three mocks base method.
func (m *MockExternalConstraint[I, F]) Three(arg0 I) F {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.threeExpects, m.ctrl, m, "Three", arg0)
}

// Three indicates an expected call of Three.
func (mr *MockExternalConstraintMockRecorder[I, F]) Three(arg0 any) *MockExternalConstraintThreeCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, F](mr.mock.ctrl.T, mr.mock, "Three", gomock.EnsureMatcher(arg0))
	mr.threeExpects = append(mr.threeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintThreeCall is the typed call wrapper for Three.
type MockExternalConstraintThreeCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, F]

// Two mocks base method.
func (m *MockExternalConstraint[I, F]) Two(arg0 I) string {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.twoExpects, m.ctrl, m, "Two", arg0)
}

// Two indicates an expected call of Two.
func (mr *MockExternalConstraintMockRecorder[I, F]) Two(arg0 any) *MockExternalConstraintTwoCall[I, F] {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[I, string](mr.mock.ctrl.T, mr.mock, "Two", gomock.EnsureMatcher(arg0))
	mr.twoExpects = append(mr.twoExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockExternalConstraintTwoCall is the typed call wrapper for Two.
type MockExternalConstraintTwoCall[I constraints.Integer, F constraints.Float] = gomock.Call1_1[I, string]
