// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/typed (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination bugreport_mock.go -package typed github.com/canonical/gomock/mockgen/internal/tests/typed Source
//

// Package typed is a generated GoMock package.
package typed

import (
	gomock "github.com/canonical/gomock/gomock"
	faux "github.com/canonical/gomock/mockgen/internal/tests/typed/faux"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock          *MockSource
	errorExpects  []*gomock.Call0_1[string]
	methodExpects []*gomock.Call0_1[faux.Return]
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockSource) Error() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.errorExpects, m.ctrl, m, "Error")
}

// Error indicates an expected call of Error.
func (mr *MockSourceMockRecorder) Error() *MockSourceErrorCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Error")
	mr.errorExpects = append(mr.errorExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceErrorCall is the typed call wrapper for Error.
type MockSourceErrorCall = gomock.Call0_1[string]

// Method mocks base method.
func (m *MockSource) Method() faux.Return {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.methodExpects, m.ctrl, m, "Method")
}

// Method indicates an expected call of Method.
func (mr *MockSourceMockRecorder) Method() *MockSourceMethodCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[faux.Return](mr.mock.ctrl.T, mr.mock, "Method")
	mr.methodExpects = append(mr.methodExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockSourceMethodCall is the typed call wrapper for Method.
type MockSourceMethodCall = gomock.Call0_1[faux.Return]
