// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/missing_import/source (interfaces: Bar)
//
// Generated by this command:
//
//	mockgen -package source -destination=../output/source_mock.go github.com/canonical/gomock/mockgen/internal/tests/missing_import/source Bar
//

// Package source is a generated GoMock package.
package source

import (
	gomock "github.com/canonical/gomock/gomock"
	source "github.com/canonical/gomock/mockgen/internal/tests/missing_import/source"
)

// MockBar is a mock of Bar interface.
type MockBar struct {
	ctrl     *gomock.Controller
	recorder *MockBarMockRecorder
	isgomock struct{}
}

// MockBarMockRecorder is the mock recorder for MockBar.
type MockBarMockRecorder struct {
	mock       *MockBar
	bazExpects []*gomock.Call1_0[source.Foo]
}

// NewMockBar creates a new mock instance.
func NewMockBar(ctrl *gomock.Controller) *MockBar {
	mock := &MockBar{ctrl: ctrl}
	mock.recorder = &MockBarMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBar) EXPECT() *MockBarMockRecorder {
	return m.recorder
}

// Baz mocks base method.
func (m *MockBar) Baz(arg0 source.Foo) {
	m.ctrl.T.Helper()
	gomock.Dispatch1_0(&m.recorder.bazExpects, m.ctrl, m, "Baz", arg0)
}

// Baz indicates an expected call of Baz.
func (mr *MockBarMockRecorder) Baz(arg0 any) *MockBarBazCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_0[source.Foo](mr.mock.ctrl.T, mr.mock, "Baz", gomock.EnsureMatcher(arg0))
	mr.bazExpects = append(mr.bazExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockBarBazCall is the typed call wrapper for Baz.
type MockBarBazCall = gomock.Call1_0[source.Foo]
