// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/panicing_test (interfaces: Foo)
//
// Generated by this command:
//
//	mockgen --destination=mock_test.go --package=paniccode go.uber.org/mock/mockgen/internal/tests/panicing_test Foo
//

// Package paniccode is a generated GoMock package.
package paniccode

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
	isgomock struct{}
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockFoo) Bar() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "Bar"))
}

// Bar indicates an expected call of Bar.
func (mr *MockFooMockRecorder) Bar() *MockFooBarCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bar", reflect.TypeOf((*MockFoo)(nil).Bar))
	return &MockFooBarCall{Call: call}
}

// MockFooBarCall is the typed call wrapper for Bar.
type MockFooBarCall = gomock.Call0_1[string]

// Baz mocks base method.
func (m *MockFoo) Baz() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "Baz"))
}

// Baz indicates an expected call of Baz.
func (mr *MockFooMockRecorder) Baz() *MockFooBazCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Baz", reflect.TypeOf((*MockFoo)(nil).Baz))
	return &MockFooBazCall{Call: call}
}

// MockFooBazCall is the typed call wrapper for Baz.
type MockFooBazCall = gomock.Call0_1[string]
