// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/gomock/mockgen/internal/tests/panicing_test (interfaces: Foo)
//
// Generated by this command:
//
//	mockgen --destination=mock_test.go --package=paniccode github.com/canonical/gomock/mockgen/internal/tests/panicing_test Foo
//

// Package paniccode is a generated GoMock package.
package paniccode

import (
	gomock "github.com/canonical/gomock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
	isgomock struct{}
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock       *MockFoo
	barExpects []*gomock.Call0_1[string]
	bazExpects []*gomock.Call0_1[string]
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Bar mocks base method.
func (m *MockFoo) Bar() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.barExpects, m.ctrl, m, "Bar")
}

// Bar indicates an expected call of Bar.
func (mr *MockFooMockRecorder) Bar() *MockFooBarCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Bar")
	mr.barExpects = append(mr.barExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFooBarCall is the typed call wrapper for Bar.
type MockFooBarCall = gomock.Call0_1[string]

// Baz mocks base method.
func (m *MockFoo) Baz() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.bazExpects, m.ctrl, m, "Baz")
}

// Baz indicates an expected call of Baz.
func (mr *MockFooMockRecorder) Baz() *MockFooBazCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Baz")
	mr.bazExpects = append(mr.bazExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockFooBazCall is the typed call wrapper for Baz.
type MockFooBazCall = gomock.Call0_1[string]
