//go:build (linux && 386) || (darwin && !cgo) || usertag

// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/build_constraint (interfaces: Empty)
//
// Generated by this command:
//
//	mockgen -package empty_interface -destination mock.go -build_constraint=(linux && 386) || (darwin && !cgo) || usertag go.uber.org/mock/mockgen/internal/tests/build_constraint Empty
//

// Package empty_interface is a generated GoMock package.
package empty_interface

import (
	gomock "go.uber.org/mock/gomock"
)

// MockEmpty is a mock of Empty interface.
type MockEmpty struct {
	ctrl     *gomock.Controller
	recorder *MockEmptyMockRecorder
	isgomock struct{}
}

// MockEmptyMockRecorder is the mock recorder for MockEmpty.
type MockEmptyMockRecorder struct {
	mock *MockEmpty
}

// NewMockEmpty creates a new mock instance.
func NewMockEmpty(ctrl *gomock.Controller) *MockEmpty {
	mock := &MockEmpty{ctrl: ctrl}
	mock.recorder = &MockEmptyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmpty) EXPECT() *MockEmptyMockRecorder {
	return m.recorder
}
