name: Run tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  go:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x] # oldest version that can build go mock and official supported go versions
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"

      - name: Vet and build
        run: |
          go vet ./...
          go build ./...

      - name: Install mockgen
        run: |
          go install github.com/canonical/gomock/mockgen

      - name: Check go.mod is tidy
        run: |
          for i in $(find $PWD -name go.mod); do
            pushd $(dirname $i)
            go mod tidy
            popd
          done
          if [ -n "$(git status --porcelain)" ]; then
            git status
            git diff
            echo
            echo "The go.mod is not up to date."
            exit 1
          fi

      - name: Check generated files are up to date
        run: |
          BASE_DIR="$PWD"
          TEMP_DIR=$(mktemp -d)
          trap "rm -rf ${TEMP_DIR}" EXIT
          cp -r . "${TEMP_DIR}/"
          cd "${TEMP_DIR}"
          for i in $(find . -name go.mod); do
            pushd $(dirname $i)
            go generate ./...
            popd
          done
          if ! diff -r . "${BASE_DIR}"; then
            echo
            echo "The generated files aren't up to date."
            echo "Update them with the 'go generate ./...' command."
            exit 1
          fi

      - name: Check panic handling
        run: |
          cd mockgen/internal/tests/panicing_test
          go test -v -tags=panictest -run TestDanger_Panics_Explicit | grep "Danger, Will Robinson!"
          go test -v -tags=panictest -run TestDanger_Panics_Implicit | grep "Danger, Will Robinson!"

      - name: Run Go Tests
        run: |
          for i in $(find $PWD -name go.mod); do
            pushd $(dirname $i)
            go test ./...
            popd
          done
