// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/mock/mockgen/internal/tests/typed_inorder (interfaces: Animal)
//
// Generated by this command:
//
//	mockgen -package typed_inorder -destination=mock.go go.uber.org/mock/mockgen/internal/tests/typed_inorder Animal
//

// Package typed_inorder is a generated GoMock package.
package typed_inorder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAnimal is a mock of Animal interface.
type MockAnimal struct {
	ctrl     *gomock.Controller
	recorder *MockAnimalMockRecorder
	isgomock struct{}
}

// MockAnimalMockRecorder is the mock recorder for MockAnimal.
type MockAnimalMockRecorder struct {
	mock *MockAnimal
}

// NewMockAnimal creates a new mock instance.
func NewMockAnimal(ctrl *gomock.Controller) *MockAnimal {
	mock := &MockAnimal{ctrl: ctrl}
	mock.recorder = &MockAnimalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimal) EXPECT() *MockAnimalMockRecorder {
	return m.recorder
}

// Feed mocks base method.
func (m *MockAnimal) Feed(arg0 string) error {
	m.ctrl.T.Helper()
	return gomock.Invoke1[error](m.ctrl.Call(m, "Feed", arg0))
}

// Feed indicates an expected call of Feed.
func (mr *MockAnimalMockRecorder) Feed(arg0 any) *MockAnimalFeedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockAnimal)(nil).Feed), arg0)
	return &MockAnimalFeedCall{Call: call}
}

// MockAnimalFeedCall is the typed call wrapper for Feed.
type MockAnimalFeedCall = gomock.Call1_1[string, error]

// GetSound mocks base method.
func (m *MockAnimal) GetSound() string {
	m.ctrl.T.Helper()
	return gomock.Invoke1[string](m.ctrl.Call(m, "GetSound"))
}

// GetSound indicates an expected call of GetSound.
func (mr *MockAnimalMockRecorder) GetSound() *MockAnimalGetSoundCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSound", reflect.TypeOf((*MockAnimal)(nil).GetSound))
	return &MockAnimalGetSoundCall{Call: call}
}

// MockAnimalGetSoundCall is the typed call wrapper for GetSound.
type MockAnimalGetSoundCall = gomock.Call0_1[string]
